### ISSUE TITLE
Missing kernel database package for 6900XT

### ISSUE THREAD

**Issue by onitake** [ROCmSoftwarePlatform/MIOpen#1999] opened 2023-02-25 10:54 UTC
While working with PyTorch, I was presented with a warning that precompiled kernels aren't installed for the system's GPU architecture:
```
MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_40.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package
```

This machine has a 6900XT, which apparently is a gfx1030 with 80 compute units.
However the package repository only contains a package for gfx1030 with 72 CUs, miopenkernels-gfx1030-36kdb, which is for the 6800XT.

Is it intended that precompiled kernels are only available for a limited set of GPUs?
If yes, I think the readme should also explain how to build and install precompiled kernel databases manually.

Or perhaps I'm using the wrong repository?
My apt source list contains this:
```
deb [arch=amd64 signed-by=/usr/share/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/debian/ jammy main
```

I should mention that PyTorch is working fine, but the warning suggest that installing the database can improve startup times.

**Comment by wsippel** [comment] 2023-02-25 12:11
Precompiled kernels exist for the "officially supported" GPUs only, which, for RDNA2, would be the Radeon Pro W6800. Not really a big deal, just means kernels for unsupported GPUs have to be compiled at runtime. They get cached so compilation only happens on the first run.

But the dev team might want to consider clearing up the debug message, it evidently causes quite a bit of confusion and bug reports, especially as general interest in AI and ML increases right now. Or, even better, officially support all AMD GPUs, not just the workstation and datacenter products, but that decision would have to be made much higher up the chain, of course.

**Comment by onitake** [comment] 2023-02-25 13:40
That is very interesting!
I had the impression that the first run was taking much longer than subsequent ones and figured it was caching some things.

Where exactly is this cache stored?
Judging from the precompiled kernel package size, it looks like it can take up quite a bit of space, so I think it would make sense to add this bit to the readme as well.

**Comment by onitake** [comment] 2023-02-25 14:33
Oh, and some more interesting facts:

The W6800(X) only has 60 CUs, according to https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units#Radeon_Pro_W6000_series
So, I wonder why there is a gfx1030_72 if it's not for supporting the RX 6800(XT)...

And there's also a W6900X with 80 CUs.

**Comment by atamazov** [comment] 2023-02-25 14:48
@wsippel Thanks for commenting here.

@onitake 
> Where exactly is this cache stored?

`$HOME/.cache/miopen/`

@junliume This is duplicate of #1606, #1709, #1995, #1996. I recommend closing this.

**Comment by onitake** [comment] 2023-02-25 15:07
You're right of course, @atamazov .
I'm sorry, I didn't see these issues, except for #1709 , which I thought was more about ROCm not finding the correct DB file for this GPU because of a bug.

That being said, I still vote for adding information about the cache to the readme, to reduce confusion about the real performance impact. I can prepare a PR, if that's ok for you?

**Comment by atamazov** [comment] 2023-03-02 22:19
@onitake 
>  I can prepare a PR, if that's ok for you?

Perfect!

**Closed as completed** 2023-03-09 22:43 UTC
