### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Looong01** [ROCmSoftwarePlatform/MIOpen#3066] opened 2024-06-19 14:02 UTC
Because ROCm has already come to Windows, we need MIOpen also come, then we can use PyTorch on Windows. Is that possible?

**Comment by mirh** [comment] 2024-06-19 15:54
Duplicate of #2668
Perhaps they are just waiting to fix #3067 before releasing 6.1.3?

**Closed as completed** 2024-06-19 15:55 UTC
