### ISSUE TITLE
Single Threaded Build Issue: Missing MIOpenPasses.h.inc

### ISSUE THREAD

**Issue by JP-Ellis** [ROCmSoftwarePlatform/MIOpen#1570] opened 2022-05-29 21:52 UTC
Over on the ROCm Arch Linux PKGBUILD repository, there has been an ongoing and difficult to debug build issue affecting users. It appears that this has been finally attributed to the lack of a parallel build when building the MIOpen source (see rocm-arch/rocm-arch#787 and rocm-arch/rocm-arch#785).

Specifically, it would appear that some of the build steps that make use of `mlir/Conversion/MIOpenPasses.h.inc` do not depend on the build steps that generate that file. In a parallel build, the generation of these files appears to happen fast enough to not be an issue, but disabling parallel builds with `-j1` may result in the order of the build being incorrect.

I will investigate this more precisely when I have time later, but for now I am creating the issue to raise some awareness.

**Comment by junliume** [comment] 2022-05-30 07:29
@jerryyin  would this be the same or similar issue as we've seen with massive parallel builds? Could be a build order dependency issue.

**Comment by pcf000** [comment] 2022-07-28 20:54
I think this issue is superseded by https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/558 , which is fixed in ROCmSoftwarePlatform/llvm-project-mlir commit 73a1136ddd267c632d6ea760a31f69a8fc7c4ec4 (July 26).

**Comment by atamazov** [comment] 2022-07-29 12:29
@pcf000 @jerryyin 

> I think this issue is superseded by https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/558 , which is fixed in ROCmSoftwarePlatform/llvm-project-mlir commit 73a1136ddd267c632d6ea760a31f69a8fc7c4ec4 (July 26).

Is it possible to verify that the issue is resolved by the abovementioned commit?

**Comment by pcf000** [comment] 2022-07-29 20:41
#787/#769 is a missing dependence from obj.MLIRMIOpenGraphXToTosa to MLIRMIOpenConversionPassIncGen.  That dependence was added in commit c2478038f2f98 on April 25, 2022, which appears in rocm-5.3.0 but not earlier tagged releases.

#785 is a missing dependence from obj.MLIRMIOpenTuning to MLIRMIOpenPassIncGen.  This commit adds that dependence.

I learned today that
  `set_property(GLOBAL PROPERTY GLOBAL_DEPENDS_DEBUG_MODE 1)`
will cause cmake to spit the dependences out to stderr.  I can see there that both dependences are now listed as simple direct dependences.

**Closed** 2022-08-08 23:59 UTC
Labels: urgency_normal
