### ISSUE TITLE
Failure observed in Openvx-neural net after #1928

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1982] opened 2023-02-15 07:27 UTC
@averinevg this issue appears after #1928 could it be a validation issue?

Repro steps:
```

% git clone https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX && cd MIVisionX/

% python3 MIVisionX-setup.py --reinstall ON

% mkdir build && cd build

% cmake .. && make -j && make install

% export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib:/opt/rocm/rpp/lib:/opt/rocm/hip/lib:/usr/local/lib

% export PATH=$PATH:/opt/rocm/bin

% cd ../../

% git clone https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX-tests

% cd MIVisionX-tests/openvx-neural-net-test-suite/neural-net-c-code-unit-test

% python3 nn-c_code-tests-prereq.py

% python3 run_NN_C_code_tests.py
```
Observations :
```
/deconvolution_layer # ./deconvolution_layer

OK: loaded 39 kernels from libvx_nn.so

OK: OpenVX using GPU device - 0:  [gfx908:sramecc+:xnack-] with 120 CUs on PCI bus 1d:00.0

MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/tensor.cpp:89: Lengths must be > 0

ERROR: fatal error occured at /tmp/MIVisionX/amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp#184
```

**Comment by junliume** [comment] 2023-02-15 07:29
@averinevg @atamazov : this may or may not be an actual defect, maybe the unit test is to test zero length tensor input?

**Comment by atamazov** [comment] 2023-02-15 12:22
The reason of the issue is either incorrect test in MIVisionX or too strict checks introduced in #1928.

@pfultz2 Cal you please confirm that the failing test is correct (i.e. zero lengths are valid in certain cases)?

@averinevg What is your opinion? Can you look into the test as well? Perhaps we shall allow zero lengths?

**Comment by atamazov** [comment] 2023-02-15 12:22
@junliume Please set an urgency label, thanks.

**Comment by pfultz2** [comment] 2023-02-15 14:05
Lengths that are 0 are invalid and can cause division by zero and other incorrect calculations in some places, which is why we have that check.

**Comment by junliume** [comment] 2023-02-15 18:51
It looks more like an incorrect test in MIVisionX @kiritigowda

**Comment by kiritigowda** [comment] 2023-02-15 22:33
@junliume we will verify the test and update this issue.

**Comment by paveltc** [comment] 2023-02-15 23:15
@junliume We have tested this on our system and found no tensors of size 0. Below is the dump from running the test case with MIOPEN_ENABLE_LOGGING_CMD=1

Using MIOpen:  2.19.0.50500-crdnnh.11263~20.04

```./deconvolution_layer 
OK: loaded 39 kernels from libvx_nn.so
OK: OpenVX using GPU device - 0: AMD Radeon RX 6800 [gfx1030] with 60 CUs on PCI bus 0c:00.0
MIOpen(HIP): Command [LogCmdFindConvolution] ./bin/MIOpenDriver conv -n 1 -c 19 -H 14 -W 14 -k 19 -y 4 -x 4 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m trans -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 19 -H 14 -W 14 -k 19 -y 4 -x 4 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m trans -g 1 -F 1 -t 1
OK: successful

**Comment by junliume** [comment] 2023-02-16 01:32
@paveltc could you check this line and make sure `data->bias_desc` is not (expected as) empty?

https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/0a4e22ab837ea4e0efcf215fe1d99cae36c6df7b/amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp#L184

@averinevg and @atamazov could you also take a look?

Update urgency because we have to get it resolved by ROCm 5.5

**Comment by atamazov** [comment] 2023-02-16 22:49
@paveltc 
> Below is the dump from running the test case with MIOPEN_ENABLE_LOGGING_CMD=1

The dump is not detailed enough. Please attach the console log obtained with the following settings:
```
export MIOPEN_ENABLE_LOGGING=1
export MIOPEN_ENABLE_LOGGING_CMD=1
export MIOPEN_LOG_LEVEL=6
```
More info at https://rocmsoftwareplatform.github.io/MIOpen/doc/html/DebugAndLogging.html

**Comment by atamazov** [comment] 2023-02-16 22:51
@paveltc ...or additional triaging is not required as https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/1040 is expected to resolve the issue?

**Comment by paveltc** [comment] 2023-02-16 23:23
@atamazov Yes, https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/1040 is expected to resolve this issue.

**Comment by averinevg** [comment] 2023-02-17 15:30
@atamazov @junliume @pfultz2 Previously (before https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1928), the check was implemented with a bug, and lengths could be 0.

**Comment by kiritigowda** [comment] 2023-02-17 23:11
TOT MIVisonX has the fix for this issue and is being pushed into 5.5 branch.

## Issue
```
OK: loaded 39 kernels from libvx_nn.so
OK: OpenVX using GPU device - 0: AMD Radeon PRO W6800 [gfx1030] with 60 CUs on PCI bus 0b:00.0
MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/tensor.cpp:89: Lengths must be > 0
ERROR: fatal error occured at /home/kiriti/develop/mivisionx-upstream/MIVisionX/amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp#184
```
## Fix
```
OK: loaded 39 kernels from libvx_nn.so
OK: OpenVX using GPU device - 0: AMD Radeon PRO W6800 [gfx1030] with 60 CUs on PCI bus 0b:00.0
OK: successful
```

**Closed as completed by kiritigowda** 2023-02-17 23:11 UTC
Labels: urgency_blocker
