### ISSUE TITLE
No precompiled kernels found for MI200

### ISSUE THREAD

**Issue by xiaoyu-work** [ROCmSoftwarePlatform/MIOpen#1600] opened 2022-06-23 06:46 UTC
Hi,

I was trying to run [this script](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/utils/install_precompiled_kernels.sh) on MI200 machine, which has gfx90a architecture. While I was not able to install the package and got error:
```
using rocminfo at /usr/bin/rocminfo
sudo apt install -y miopenkernels-gfx90a-110kdb
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]          
Get:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]        
Get:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                          
Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease                                                  
Hit:6 https://repo.radeon.com/amdgpu/22.10.1/ubuntu focal InRelease                                  
Hit:7 https://repo.radeon.com/rocm/apt/5.1.1 ubuntu InRelease
Fetched 336 kB in 1s (634 kB/s)
Reading package lists... Done
Building dependency tree      
Reading state information... Done
34 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree      
Reading state information... Done
E: Unable to locate package miopenkernels-gfx90a-110kdb
```

Does this precompiled kernel package support MI200 gfx90a architecture? Or which package should I install?

Thanks.

**Comment by xuhuisheng** [comment] 2022-06-23 08:02
there is no kdb
http://repo.radeon.com/rocm/apt/5.1.1/pool/main/m/miopenkernels-gfx90a-110/

**Comment by junliume** [comment] 2022-06-23 17:56
@xiaoyu-work could you please try the following instead?
`sudo apt install -y miopenkernels-gfx90a-110pkg`
The issue is fixed in develop branch and ready for the next release.

**Comment by xiaoyu-work** [comment] 2022-07-11 22:00
Hi @junliume , apt install -y miopenkernels-gfx90a-110 doesn't work for new released ROCm 5.2 image: https://hub.docker.com/layers/dev-ubuntu-20.04/rocm/dev-ubuntu-20.04/5.2-complete/images/sha256-4030c8af0c06c286174758523dabe4b3850bf72d4a8c1ef275d3ec69aa475f65?context=explore. Can you fix this?

**Comment by junliume** [comment] 2022-07-12 21:19
@xiaoyu-work 
could you please try:
```
apt install -y miopenkernels-gfx90a-110kdb
```
we will fix the inconsistency in the script. CC: @JehandadKhan

**Comment by xiaoyu-work** [comment] 2022-07-13 21:18
Thanks @junliume . This package name works. Which package name will be the final one?

**Comment by junliume** [comment] 2022-08-17 07:30
#1678  dealt with this issue

**Closed by junliume** 2022-08-17 07:30 UTC
