### ISSUE TITLE
Regression in direct naive gpu convolution caused false positive test breakages

### ISSUE THREAD

**Issue by jerryyin** [ROCmSoftwarePlatform/MIOpen#1576] opened 2022-06-02 18:14 UTC
I believe gpu reference convolution kernel for bwd is broken after #1532. I found this via bisecting into MIOpen commit history.

### Before #1532 

Command
```bash
$ git checkout f3b4f1898
$ MIOPEN_FIND_MODE=1 MIOPEN_DRIVER_USE_GPU_REFERENCE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvDirectNaiveConvBwd ./bin/MIOpenDriver convfp16 --forw 2 --in_layout NCHW --out_layout NCHW --fil_layout NCHW -n 256 -c 1024 -H 14 -W 14 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
```

Output
```bash
MIOpenDriver convfp16 --forw 2 --in_layout NCHW --out_layout NCHW --fil_layout NCHW -n 256 -c 1024 -H 14 -W 14 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpen Backward Data Conv. Algorithm: 1, Solution: 86/ConvDirectNaiveConvBwd
GPU Kernel Time Backward Data Conv. Elapsed: 245.581238 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv1x1u1, 256, 1024, 1, 1, 256, 14, 14,  26306674688, 134742016, 25690112, 107, 1, 245.581238
Backward Convolution Data Verifies OK on GPU reference (0)
```

### After #1532 + #1567 + #1568

Command
```bash
$ git checkout a22af06
$ MIOPEN_FIND_MODE=1 MIOPEN_DRIVER_USE_GPU_REFERENCE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvDirectNaiveConvBwd ./bin/MIOpenDriver convfp16 --forw 2 --in_layout NCHW --out_layout NCHW --fil_layout NCHW -n 256 -c 1024 -H 14 -W 14 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
```

Output
```bash
MIOpenDriver convfp16 --forw 2 --in_layout NCHW --out_layout NCHW --fil_layout NCHW -n 256 -c 1024 -H 14 -W 14 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpen Backward Data Conv. Algorithm: 1, Solution: 86/ConvDirectNaiveConvBwd
GPU Kernel Time Backward Data Conv. Elapsed: 245.720154 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv1x1u1, 256, 1024, 1, 1, 256, 14, 14,  26306674688, 134742016, 25690112, 107, 1, 245.720154
Backward Convolution Data FAILED: 0.487108 > 0.0082
```

### Summary

Based on #1567 and #1568 has nothing to do with gpu reference kernel, I suspect it is broken by #1532. In the before/after comparison I used the `ConvDirectNaiveConvBwd`, however, it can be reproduced by (probably arbitrary kernels). Using `ConvMlirIgemmBwdXdlops` I can reproduce the same behavior. Because of this, MLIR CI is in a broken stage (due to gpu reference kernel validation), I have temporarily reverted MIOpen commit to an earlier one to unblock pull request. 

CC: @aska-0096 @carlushuang

**Comment by aska-0096** [comment] 2022-06-03 06:12
Thanks for the finding. 
I can reproduce your problem. This occurs only when using gpu verification, cpu verifaction kernel is ok. let me check it.

**Comment by aska-0096** [comment] 2022-06-03 11:00
Hi @jerryyin @junliume 
The reason to cause verification failed is gpu reference kernel data lost during cast and store into the host tensor, they are all zero. That's why bwd fp32 can work(Type of GPU and Type of Ref are equal, no need to cast), but fp16 and bfp16 failed.
I can repair it by change the way to construct the tensor which used to hold the gpu reference data, let me create the hotfix PR.

**Comment by jerryyin** [comment] 2022-06-03 15:19
@aska-0096 Nice job in finding out the bug quickly! How did you realize the bug in such an unexpected place? Did you dump the input/filter and figured out they are all zeros, and start from there?

**Comment by aska-0096** [comment] 2022-06-03 15:38
> @aska-0096 Nice job in finding out the bug quickly! How did you realize the bug in such an unexpected place? Did you dump the input/filter and figured out they are all zeros, and start from there?

Exactly. 
I worked in this procedure: 
1. test bwd conv in other data type and found that fp32 works well, meanwhile I check the miopen log info to make sure correct kernel invoked. 
2. print the value of gpu reference tensor hold. -> found they are all zero.
3. check the verify part -> found this bug.

**Comment by jerryyin** [comment] 2022-06-13 14:49
Per @aska-0096 here: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1578#issuecomment-1146089410, I believe another missing item is to get test_gpu_reference_kernel tracked under a smoke stage. (right now it seems to be a target not tracked by automated test but can only run manually?)

**Comment by jerryyin** [comment] 2022-06-13 14:49
Per @aska-0096 here: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1578#issuecomment-1146089410, I believe another missing item is to get test_gpu_reference_kernel tracked under a smoke stage. (right now it seems to be a target not tracked by automated test but can only run manually?)

**Comment by jerryyin** [comment] 2022-06-13 16:04
Reopening for clarification of the last comment. I'd be willing to contribute if needed.

**Comment by atamazov** [comment] 2022-06-15 21:53
@jerryyin 
> ### I believe another missing item is to get test_gpu_reference_kernel tracked under a smoke stage.

`test_gpu_reference_kernel` is not related to this issue (the reason of it is a bug in MIOpenDriver), therefore regression tests for this issue do not touch `test_gpu_reference_kernel`.

`test_gpu_reference_kernel` is used in smoke tests as usual.

Note that for INT8 and BF16 all tests except those explicitly listed in SKIP_ALL_EXCEPT_TESTS are disabled (this is legacy stuff 😉), so `test_gpu_reference_kernel` is not enabled for these types. See here:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/edae4e69f49059c7488fbe5d9fad087f07dae4df/test/CMakeLists.txt#L183-L193

> ### (right now it seems to be a target not tracked by automated test but can only run manually?)

`test_gpu_reference_kernel` is automatically tracked by this line:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/edae4e69f49059c7488fbe5d9fad087f07dae4df/test/CMakeLists.txt#L353 then by
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/edae4e69f49059c7488fbe5d9fad087f07dae4df/test/CMakeLists.txt#L379-L382 More info at https://github.com/ROCmSoftwarePlatform/MIOpen/blob/edae4e69f49059c7488fbe5d9fad087f07dae4df/test/CMakeLists.txt#L290

>  ### I'd be willing to contribute if needed.

You are always welcome))

**Comment by aska-0096** [comment] 2022-06-16 01:47
> @jerryyin
> 
> > ### I believe another missing item is to get test_gpu_reference_kernel tracked under a smoke stage.
> 
> `test_gpu_reference_kernel` is not related to this issue (the reason of it is a bug in MIOpenDriver), therefore regression tests for this issue do not touch `test_gpu_reference_kernel`.
> 
> `test_gpu_reference_kernel` is used in smoke tests as usual.
> 
> Note that for INT8 and BF16 all tests except those explicitly listed in SKIP_ALL_EXCEPT_TESTS are disabled (this is legacy stuff 😉), so `test_gpu_reference_kernel` is not enabled for these types. See here:
> 
> https://github.com/ROCmSoftwarePlatform/MIOpen/blob/edae4e69f49059c7488fbe5d9fad087f07dae4df/test/CMakeLists.txt#L183-L193
> 
> > ### (right now it seems to be a target not tracked by automated test but can only run manually?)
> 
> `test_gpu_reference_kernel` is automatically tracked by this line:
> 
> https://github.com/ROCmSoftwarePlatform/MIOpen/blob/edae4e69f49059c7488fbe5d9fad087f07dae4df/test/CMakeLists.txt#L353
> 
> then by
> https://github.com/ROCmSoftwarePlatform/MIOpen/blob/edae4e69f49059c7488fbe5d9fad087f07dae4df/test/CMakeLists.txt#L379-L382
> 
> More info at
> https://github.com/ROCmSoftwarePlatform/MIOpen/blob/edae4e69f49059c7488fbe5d9fad087f07dae4df/test/CMakeLists.txt#L290
> 
> > ### I'd be willing to contribute if needed.
> 
> You are always welcome))

Thanks to @atamazov 's response, it gave us a structured overview of MIOpen ctest, which would be beneficial for any MIOpen developer, I recommend adding it to the MIOpen wiki. Great work!
cc. @junliume

**Comment by atamazov** [comment] 2022-06-16 15:20
> ...a structured overview of MIOpen ctest, which would be beneficial for any MIOpen developer, I recommend adding it to the MIOpen wiki...

In wiki, we can just add a link to the comment (https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1576#issuecomment-1156983158) under the header like "_Structured overview of of test/CMakeLists.txt_". Easy and fast))

**Comment by aska-0096** [comment] 2022-06-17 02:24
Yes, I create this [page](https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/Structured-overview-of-of-test-CMakeLists.txt)
BTW, I think there are no topic left in this ticket, let me close it.

**Closed by aska-0096** 2022-06-17 02:24 UTC
Labels: enhancement, urgency_normal

**Comment by jerryyin** [comment] 2022-06-17 13:58
Thank you @atamazov for your thorough explanation, `file(GLOB TESTS *.cpp)` is not something I'm aware of and I'm glad to learn about this.

Also thanks @aska-0096 jumping in and handle this immediately after reported.
