### ISSUE TITLE
hip build option failing with 4.5.2 release

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/MIOpen#1416] opened 2022-02-10 04:18 UTC
OpenCL build ok but wiht HIP:

```
cmake -DMIOPEN_BACKEND=HIP -DMIOPEN_HIP_COMPILER=/opt/rocm/llvm/bin/clang++ ..
...
make -j8
[  0%] Built target sqlite_memvfs
[  0%] Built target addkernels
[  0%] Built target tidy-rm-fixit-dir
[  0%] Built target tidy-make-fixit-dir
[  0%] Built target tidy-base
[  0%] clang-tidy: Running clang-tidy on target addkernels.cpp...
[  0%] clang-tidy: Running clang-tidy on target include_inliner.cpp...
[  1%] Building CXX object src/CMakeFiles/MIOpen.dir/__/kernel.cpp.o
[  1%] Building CXX object src/CMakeFiles/MIOpen.dir/__/kernel_includes.cpp.o
[  1%] Building CXX object src/CMakeFiles/MIOpen.dir/buffer_info.cpp.o
[  1%] Building CXX object src/CMakeFiles/MIOpen.dir/check_numerics.cpp.o
[  1%] Building CXX object src/CMakeFiles/MIOpen.dir/convolution.cpp.o
[  1%] Building CXX object src/CMakeFiles/MIOpen.dir/convolution_api.cpp.o
c++: error: unrecognized command line option '--offload-arch=gfx900'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx900'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx900'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx906'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx900'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx906'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx906'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx900'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx900'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx908'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx908'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx906'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx908'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx906'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx906'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx90a'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx90a'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx908'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx90a'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx908'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx908'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx1030'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx1030'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx90a'; did you mean '--offload-abi=ilp32'?
src/CMakeFiles/MIOpen.dir/build.make:16892: recipe for target 'src/CMakeFiles/MIOpen.dir/__/kernel_includes.cpp.o' failed
make[2]: *** [src/CMakeFiles/MIOpen.dir/__/kernel_includes.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/CMakeFiles/MIOpen.dir/build.make:16918: recipe for target 'src/CMakeFiles/MIOpen.dir/check_numerics.cpp.o' failed
make[2]: *** [src/CMakeFiles/MIOpen.dir/check_numerics.cpp.o] Error 1
c++: error: unrecognized command line option '--offload-arch=gfx1030'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx90a'; did you mean '--offload-abi=ilp32'?
src/CMakeFiles/MIOpen.dir/build.make:16905: recipe for target 'src/CMakeFiles/MIOpen.dir/buffer_info.cpp.o' failed
make[2]: *** [src/CMakeFiles/MIOpen.dir/buffer_info.cpp.o] Error 1
c++: error: unrecognized command line option '--offload-arch=gfx90a'; did you mean '--offload-abi=ilp32'?
c++: error: unrecognized command line option '--offload-arch=gfx1030'; did you mean '--offload-abi=ilp32'?
src/CMakeFiles/MIOpen.dir/build.make:16879: recipe for target 'src/CMakeFiles/MIOpen.dir/__/kernel.cpp.o' failed
make[2]: *** [src/CMakeFiles/MIOpen.dir/__/kernel.cpp.o] Error 1
c++: error: unrecognized command line option '--offload-arch=gfx1030'; did you mean '--offload-abi=ilp32'?
src/CMakeFiles/MIOpen.dir/build.make:16931: recipe for target 'src/CMakeFiles/MIOpen.dir/convolution.cpp.o' failed
make[2]: *** [src/CMakeFiles/MIOpen.dir/convolution.cpp.o] Error 1
c++: error: unrecognized command line option '--offload-arch=gfx1030'; did you mean '--offload-abi=ilp32'?
src/CMakeFiles/MIOpen.dir/build.make:16944: recipe for target 'src/CMakeFiles/MIOpen.dir/convolution_api.cpp.o' failed
make[2]: *** [src/CMakeFiles/MIOpen.dir/convolution_api.cpp.o] Error 1
CMakeFiles/Makefile2:4492: recipe for target 'src/CMakeFiles/MIOpen.dir/all' failed
make[1]: *** [src/CMakeFiles/MIOpen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
19221 warnings generated.
/root/ROCm-4.5/MIOpen/addkernels/include_inliner.cpp:106:5: warning: kernel performance could be improved by unrolling this loop with a '#pragma unroll' directive [altera-unroll-loops]
    while(!input.eof())
    ^
/root/ROCm-4.5/MIOpen/addkernels/include_inliner.cpp:206:5: warning: kernel performance could be improved by unrolling this loop with a '#pragma unroll' directive [altera-unroll-loops]
    while(item->included_from != nullptr)
    ^
[  1%] Built target tidy-target-addkernels-include_inliner_cpp
20700 warnings generated.
/root/ROCm-4.5/MIOpen/addkernels/addkernels.cpp:72:13: warning: kernel performance could be improved by unrolling this loop with a '#pragma unroll' directive [altera-unroll-loops]
            for(; j < end; j++)
            ^
/root/ROCm-4.5/MIOpen/addkernels/addkernels.cpp:244:13: warning: kernel performance could be improved by unrolling this loop with a '#pragma unroll' directive [altera-unroll-loops]
            while(++i < argsn)
            ^
[  1%] Built target tidy-target-addkernels-addkernels_cpp
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
root@nonroot-SYS-7049GP-TRT:~/ROCm-4.5/MIOpen/build# 
```

**Comment by junliume** [comment] 2022-02-10 08:53
@atamazov  could you please take a look? I cannot reproduce it locally and hopefully @gggh000 could you please provide full log and steps to reproduce?

**Comment by junliume** [comment] 2022-02-13 20:00
@gggh000 are you still experiencing the issue or has it been resolved?
I have tested the following script and it should work fine with HIP backend.
Hence: replace `/root` with your home directory if necessary
```
cd /root && git clone -b develop https://github.com/ROCmSoftwarePlatform/MIOpen && cd MIOpen && \
mkdir -p install_dir && cmake -P install_deps.cmake --minimum --prefix /root/MIOpen/install_dir && \
mkdir -p build && cd build && export CXX=/opt/rocm/llvm/bin/clang++ && \
cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/;/opt/rocm/hip;/root/MIOpen/install_dir" .. && \
make -j 48 package && dpkg -i *.deb && make -j 24 check

**Comment by junliume** [comment] 2022-02-14 22:50
@gggh000 I would recommend deleting the build folder and try again, it looks like wrong C++ toolset is picked up.
Please re-open the issue if the issue is not resolved with a fresh process. Thanks!

**Closed by junliume** 2022-02-14 22:50 UTC
