### ISSUE TITLE
Tensor layout NHWC bug when using test_conv2d and MIOpendriver

### ISSUE THREAD

**Issue by iq136boy** [ROCmSoftwarePlatform/MIOpen#1946] opened 2023-01-26 19:26 UTC
There is a bug in test_conv2d.  The input argument "--in_layout NHWC" did not change the tensor layout to NHWC. During the run, the tensor layout still NCHW, which result in the failed of running CK kernels which only accept NHWC tensor as input.
The same bug also appears in MIOpendriver.
Take the following driver command as an example:
**MIOPEN_DRIVER_USE_GPU_REFERENCE=1 MIOPEN_FIND_MODE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvHipImplicitGemmFwdXdlops ./bin/MIOpenDriver conv -g 1 -n 256 -c 192 -H 28 -W 28 -k 192 -x 3 -y 3 --in_layout NHWC --out_layout NHWC --fil_layout NHWC -F 1**

And add the print info in ValidateGroupCount() in convolutioncol.cpp:
**std::cout<<"xDesc.GetLayout_str(): "<<xDesc.GetLayout_str()<<std::endl;**

The std output is:
**xDesc.GetLayout_str(): NCHW**

which should be NHWC.

**Comment by atamazov** [comment] 2023-01-27 22:43
It seems like test_conv2d supports NHWC correctly. More details tomorrow.

**Comment by atamazov** [comment] 2023-01-27 23:47
I do not see any problems with MIOpenDriver either.

**Comment by atamazov** [comment] 2023-01-27 23:51
@iq136boy Please add `MIOPEN_LOG_LEVEL=6` at the beginning of the command and attach the resulting log to this ticket.

I see lines like
```
...Looking for key 192-28-28-3x3-192-26-26-256-0x0-1x1-1x1-0-NHWC-NHWC-NHWC-FP32-F in cache...
```
which is a sign that NHWC layout is passed to the library correctly (and the library works fine).

**Comment by atamazov** [comment] 2023-01-27 23:57
[Off-topic] @iq136boy BTW The library never prints to stdout. Logging should be carefully considered first. Secondly, the implementation of logging should obey some rules, see #1949 for more info.

**Comment by atamazov** [comment] 2023-01-30 12:20
@junliume Let's close this unless the information requested at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1946#issuecomment-1407198523 is arrived in a week.

**Comment by junliume** [comment] 2023-01-31 06:39
@iq136boy please follow up with the above comments :)

**Comment by JehandadKhan** [comment] 2023-02-07 18:18
I think there is still an issue and both @atamazov  and @iq136boy  are correct. The difference is that the key printed is from the convolution problem description, which does report it correctly. However, the tensor descriptors have the incorrect layout set in them. 

This creates a confusion since the solver needs to specify strides to the CK API for it to be able to traverse the tensors correctly. @iq136boy has faced this phenomenon and perhaps we can work to fix this discrepancy.

**Comment by JehandadKhan** [comment] 2023-02-07 18:19
> [Off-topic] @iq136boy BTW The library never prints to stdout. Logging should be carefully considered first. Secondly, the implementation of logging should obey some rules, see #1949 for more info.

The print statements are in a local branch to assist debugging, if they make their way into a PR we can point it out then.

**Comment by JehandadKhan** [comment] 2023-02-07 18:37
Upon further investigation, we have discovered that the strides in the tensor descriptor are indeed NHWC however, when the `GetLayout` method of the tensor is called, it report NCHW.

**Comment by atamazov** [comment] 2023-02-08 00:15
@iq136boy @JehandadKhan Is it possible to reproduce the bug reported above or this is only a code quality issue?

@JehandadKhan IIRC the strides can be stored in the tensor descriptor in any (but fixed) order. NCHW is no better than NHWC. The layout depends on relationships between strides (and this is how TensorDescriptor::GetLayout() works).

**Comment by JehandadKhan** [comment] 2023-02-08 00:17
@atamazov Is it acceptable for `TensorDescriptor::GetLayout()` to return NCHW when the layout has been marked as NHWC ?

**Comment by atamazov** [comment] 2023-02-08 08:58
@JehandadKhan Maybe I do not understand the problem fully (and therefore asking for reproduce instructions above).

> Is it acceptable for `TensorDescriptor::GetLayout()` to return NCHW when the layout has been marked as NHWC ?

Basically not, but this depend on **_where_** the layout is marked as NHWC. Is it marked in the same instance of TensorDescriptor? 

Well, it looks like the following ctor:
```C++
// Main private constructor
TensorDescriptor::TensorDescriptor(miopenDataType_t t,
                                   miopenTensorLayout_t layout_in,
                                   const std::vector<std::size_t>& lens_in,
                                   const std::vector<std::size_t>& strides_in,
                                   bool use_strides)
```
allows for such a behavior -- when strides_in do not match layout_in (and use_strides is true). Layout is simply initialized from layout_in regardless of values in strides_in. @iq136boy @JehandadKhan is that the problem you have in mind?

This ctor is missing the consistency check since the beginning (#1532)

@aska-0096 @carlushuang @DrizztDoUrden @averinevg Please have a look here. What do you think?

**Comment by JehandadKhan** [comment] 2023-02-08 16:25
@iq136boy Can you please provide a branch to reproduce the issue?

**Comment by iq136boy** [comment] 2023-02-08 18:24
> @iq136boy Can you please provide a branch to reproduce the issue?

@JehandadKhan . Yes. I am working on the reproduce branch and steps.

**Comment by iq136boy** [comment] 2023-02-08 18:35
Steps to reproduce:

MIOpen branch:
https://github.com/ROCmSoftwarePlatform/MIOpen/tree/dfeng/ck_group_conv_fwd

Work station:
****

Docker:
sudo docker run -it --network=host -v $HOME/dfeng:/dfeng --privileged --rm --device=/dev/kfd --device /dev/dri:/dev/dri:rw  --volume /dev/dri:/dev/dri:rw --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined rocm/miopen:dfeng_ck_0345963ee

Steps:
build miopen inside docker:
cd to miopen directory
mkdir build && cd build && export CXX=/opt/rocm/llvm/bin/clang++ && cmake  -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/;/opt/rocm/hip;../install_dir" .. && make -j 64

build test_conv2d:
make test_conv2d

test case:
MIOPEN_FIND_MODE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvHipImplicitGemmGroupFwdXdlops ./bin/test_conv2d --float --disable-backward-data --disable-backward-weights --verbose --input 256 192  28 28 --weights 192  192  3 3 --output_type fp32 --in_layout NHWC --fil_layout NHWC --out_layout NHWC --pads_strides_dilations 1 1 1 1 1 1  --group-count 32

Note:
I only add two std cout to print the tensor layout info.
The output is sth like the following:
***********run ck solution**********
****************************problem.conv_problem.GetInLayout(): NHWC
****************************xDesc.GetLayout_str(): NCHW**

**Comment by atamazov** [comment] 2023-02-08 23:22
@iq136boy Please remove IP address and username from your previous comment.

**Comment by atamazov** [comment] 2023-02-22 20:37
@iq136boy You should use `xDesc.GetLayout(xDesc.GetLayout_str())`. AFAIU `GetLayout_str()` returns layout of lengths that reside in the tensor instance, i.e. it describes the order of _lengths_ in the `std::vector<std::size_t> lens`. The actual _layout of tensor_ is computed by `GetLayout()`, which also takes the strides into account. This is complicated topic. See https://github.com/ROCmSoftwarePlatform/MIOpen/pull/343#discussion_r472522366 for more info.

Please also refer to #343, #767, #1532 for more details.

I think this can be closed.

/cc @aska-0096 @jerryyin @pfultz2

**Comment by atamazov** [comment] 2023-02-22 20:43
TODO I think we need to clarify the semantics of `GetLayout_str()` and, possibly, rename it.

**Comment by jerryyin** [comment] 2023-02-22 21:26
@atamazov `GetLayout()` was designed to compute the layout with default ordering of all labels. So the right way to call it would be to give it that string. The way we define the natural ordering is:
 - For 4d tensor, it should use `xDesc.GetLayout("NCHW")`
 - For 5d tensor, it should use `xDesc.GetLayout("NCDHW")`

It doesn't meant to get it from the label that was already re-arranged (seems that `GetLayout_str()` would not just return an ordered layout string, those two should not be used together.

----

We used went through a whole lot of trouble just not to cache the layout as string in tensor descriptor (but only cache it in problem description). Now that we cache it anyways, we bump to this kind of incoherency. I will have to let #1532 take the blame.

I think the root cause of the problem is due to `TensorDescriptor` was constructed in a constructor that didn't take the external passed in layout for some reason. So that got initialized to a default `GetDefaultLayout()`. All this code including `GetLayout_str()` was added when NCHWc support was added, I think @aska-0096 is a better candidate in answering this.

**Comment by atamazov** [comment] 2023-02-23 21:56
@jerryyin Thanks for feedback. @aska-0096 @pfultz2 May I ask for your opinion?

**Comment by aska-0096** [comment] 2023-02-24 08:51
Hi @atamazov , I'm trying to reproduce the issue first then dive into root cause.

**Comment by aska-0096** [comment] 2023-02-27 06:19
Hi @iq136boy , here is the latest update:

First of all, whenever you want to report a MIOpen issue, export MIOPEN_LOG_LEVEL=6, copy and paste the logging information to your issue description, it really help us to shot your problem.

Second, your provided docker can not work to reproduce the error, as CK request ROCm 5.4.1 while your docker only have 5.3.0.

Third, make your issue description accurate, though your title is test_conv2d fail, the fact is your solver failed. Try following command, the test passed correctly:

`MIOPEN_DRIVER_USE_GPU_REFERENCE=1 MIOPEN_FIND_MODE=1 MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvDirectNaiveConvFwd ./bin/MIOpenDriver conv -g 1 -n 256 -c 192 -H 28 -W 28 -k 192 -x 3 -y 3 --in_layout NHWC --out_layout NHWC --fil_layout NHWC -F 1`

I also noticed that you are the owner of CK integration to MIOpen, who responsible for this solver `ConvHipImplicitGemmFwdXdlops ` integration, so probably you are not integrate your solver correctlly and it is your work to fix it.


The reason why you get descriptor return NCHW beacuse:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/aa087c18fdd154465a04a3f55062804fa97498bf/test/conv_common.hpp#L2150-L2186

It's a function added by @carlushuang , which makes MIOpen support NHWC layout in very short time at that emergency request moment. It reorder the tensor layout of test convolution problem into NCHW fashion, to meet the MIOpen layout legacy. Yes, at the very beginning, MIOpen only support NCHW layout, the tensors and related APIs use NCHW as default implicitly, which makes us feel too hard to refactor host-side API compatible with NHWC and any other layouts. 
So, our solution is to record "Real" layout in `ProblemDescription ` struct while "NCHW" stored in `TensorDescriptor`, exactlly what you seen in your printout. Naturally, Solver invoker staff should utilize the real information in `ProblemDescription `.

cc: @atamazov , @junliume

**Comment by carlushuang** [comment] 2023-03-01 05:12
I agree with @jerryyin . We used to spend a lot of time discussing not caching the layout string, but compute the layout. After `NCHWc` layout supported seems break this rule. And a mixture usage of `GetLayout_str()` and `GetLayout()` may result in failure.
The problem is in `ProblemDescription`, we will use `ComputeInLayout/ComputeOutLayout/ComputeWeightsLayout` to actually COMPUTE the layout, but the code is:

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/aa087c18fdd154465a04a3f55062804fa97498bf/src/include/miopen/conv/problem_description.hpp#L200-L210

cc @aska-0096 

@iq136boy @JehandadKhan  the layout information in tensor descriptor is always `NCHW` or `NCDHW` for non vectored layout. The actual layout is computed out by stride and length. There is a lot lot of discussions on the design, please refer to #343 #767 #1532

**Comment by iq136boy** [comment] 2023-03-08 14:15
Hi @aska-0096, thanks for your [comments](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1946#issuecomment-1445774842). I opened this issue because I observed the layout difference between tensor descriptor and problem description. I do not know the support of NHWC is a short term solution for emergency request. So I discussed this with Jehandad and we thought it might be a bug. Now I understand the difference after your explanation.  In summary, I should always use the layout information in problem description instead of tensor descriptor to get the correct layout info. I will close this issue. And, one thing can be done is to document this layout difference somewhere (if not yet) so that it won't cause the confusion later for someone else. Thanks.
cc: @junliume, @atamazov

**Closed as completed** 2023-03-08 14:16 UTC
Labels: bug, urgency_high

**Comment by atamazov** [comment] 2023-03-08 19:07
@iq136boy I think this ticket can be considered part of developer's documentation.

**Comment by atamazov** [comment] 2023-03-08 19:09
@carlushuang 
> And a mixture usage of GetLayout_str() and GetLayout() may result in failure.

We need a way to get layout from tensor. If `td.GetLayout(td.GetLayout_str())` is not reliable, then we should invent some other, reliable way. Shall we open a ticket, what do you think?

**Comment by atamazov** [comment] 2023-03-08 19:17
[off-topic] @iq136boy wrt https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1946#issuecomment-1460221949 - Huge quotations eat screen space. I would recommend using _links_ to comments or hiding quotations inside collapsible sections.
```
<details><summary><b><i>HEADLINE OF QUOTE</i></b></summary><hr>

...
Huge quotation
...
<hr></details>
```

**Comment by iq136boy** [comment] 2023-03-08 19:58
@atamazov  Thanks.  I edited my comment based on your [suggestion](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1946#issuecomment-1460726020)
