### ISSUE TITLE
[90a][db][question]Did database log the wrong workspace size?

### ISSUE THREAD

**Issue by shaojiewang** [ROCmSoftwarePlatform/MIOpen#1429] opened 2022-02-16 09:35 UTC
In our db, the logged workspaceSize seems wrong. In file src/kernels/gfx90a68.HIP.fdb.txt, line 83635, it logged the workspacesize with "244112512", but the right number should be "244112640". 
The right one should be 
```64-112-112-7x7-3-224-224-128-3x3-2x2-1x1-0-NCHW-FP16-W=miopenConvolutionBwdWeightsAlgoImplicitGEMM:ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC,1.64945,244112640,miopenConvolutionBwdWeightsAlgoImplicitGEMM,<unused>```
but I got
```64-112-112-7x7-3-224-224-128-3x3-2x2-1x1-0-NCHW-FP16-W=miopenConvolutionBwdWeightsAlgoImplicitGEMM:ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC,1.62112,244112512,miopenConvolutionBwdWeightsAlgoImplicitGEMM,not used;miopenConvolutionBwdWeightsAlgoDirect:ConvOclBwdWrW2<1>,3.63024,2408448,miopenConvolutionBwdWeightsAlgoDirect,not used;miopenConvolutionBwdWeightsAlgoGEMM:GemmWrwUniversal,7.07679,3687936,miopenConvolutionBwdWeightsAlgoGEMM,not used```

It will cause a failure in https://github.com/ROCmSoftwarePlatform/MIOpen/blob/349928c032a42275a64a1f39c10c83daf20c1d75/src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp#L1134. Because the logged workspace size is not equal to the computed workspace size.
Test config:
./bin/MIOpenDriver convfp16 -n 128 -c 3 -H 224 -W 224 -k 64 -y 7 -x 7 -p 3 -q 3 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 4 -t 1

@junliume @atamazov Could you please find some one to check the problem?

**Comment by junliume** [comment] 2022-02-16 15:16
@cderb @JehandadKhan this issue might also be related to https://ontrack-internal.amd.com/browse/SWDEV-321007

**Comment by JehandadKhan** [comment] 2022-02-16 16:27
Thanks @shaojiewang. This does look like a bug.

**Comment by junliume** [comment] 2022-02-22 20:23
@shaojiewang with #1434 and #1437 both merged in develop branch, could you check if the issue is resolved? Thanks!

**Comment by atamazov** [comment] 2022-02-22 23:23
There is https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1354 which directly modifies fdb in order to resolve #1349 without retuning. It blindly adds 3*255 bytes to workspace size, which should be enough to align 4 sub-buffers.

**_There is no need to add padding for the most recent buffer because there is no buffer after it._**

I suspect that the reason of the issue is that `MultiBufferWorkspaceTraits::MultiBufferWorkspaceTraits()` wants too much padding. It adds padding for all four buffers which may exceed 3*255.

I think that proper fix should remove adding padding for the last sub-buffer. `MultiBufferWorkspaceTraits::GetSize()` should return offset of the beginning of the last sub-buffer + the size of the last sub-buffer. **_Basically, no other fixes required._**

**Comment by atamazov** [comment] 2022-02-22 23:25
There is no harm in #1434 and 1437, but the proper fix should be applied as well as soon as time permits.

**Comment by shaojiewang** [comment] 2022-02-23 01:23
> There is #1354 which directly modifies fdb in order to resolve #1349 without retuning. It blindly adds 3*255 bytes to workspace size, which should be enough to align 4 sub-buffers.

In #1354 , only [gfx90a6e.HIP.fdb.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1354/files#diff-2f8a22ec817c2920d8d6b5872234365e252c7513870e073538692729d5fc5eb8) is changed, but I think gfx90a68.HIP.fdb.txt and gfx90878.HIP.fdb.txt should also be changed because these archs are using same solver.

> 
> **_There is no need to add padding for the most recent buffer because there is no buffer after it._**
> 
> I think that the proper fix should remove adding padding for the last sub-buffer. `MultiBufferWorkspaceTraits::GetSize()` should return offset of the beginning of the last sub-buffer + the size of the last sub-buffer. **_Basically, no other fixes required._**

Yes, I agree. I will open an another PR to avoid too much paddings.

**Comment by shaojiewang** [comment] 2022-02-23 01:23
> There is no harm in #1434 and #1437, but the proper fix should be applied as well as soon as time permits.

Yes, you're right. I'll do it.

**Comment by shaojiewang** [comment] 2022-02-23 02:00
> @shaojiewang with #1434 and #1437 both merged in develop branch, could you check if the issue is resolved? Thanks!

Hi, no failure observed. Thanks.

**Comment by atamazov** [comment] 2022-02-23 14:27
Thank you very much, guys. Actually I missed "too much padding" during review (well, I've noticed it but wrongly decided that there is no harm).

**Closed** 2022-03-15 05:14 UTC
Labels: bug, urgency_blocker
