### ISSUE TITLE
Faulting configs (tested on gfx906 60)

### ISSUE THREAD

**Issue by cderb** [ROCmSoftwarePlatform/MIOpen#311] opened 2020-06-24 00:11 UTC
`MIOPEN_LOG_LEVEL=7 MIOPEN_DEBUG_FIND_ONLY_SOLVER=55 MIOPEN_DEBUG_CONV_GEMM=0 MIOPEN_DEBUG_CONV_FFT=0 MIOpenDriver convfp16 -F 2 --pad_h 1 --out_channels 64 --fil_w 3 --dilation_w 1 --fil_h 3 --in_h 224 --conv_stride_w 1 --group_count 1 --in_channels 64 --in_w 224 --dilation_h 1 --conv_stride_h 1 --pad_w 1 --batchsize 512 --pad_mode default --mode conv --fil_d 1 --in_d 1 --spatial_dim 2 --conv_stride_d 1 -^ 1 -$ 0 --trans_output_pad_d 0 2>&1`
Convolution failure
[0.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4826637/0.log)

`MIOPEN_LOG_LEVEL=7 MIOPEN_DEBUG_FIND_ONLY_SOLVER=55 MIOPEN_DEBUG_CONV_GEMM=0 MIOPEN_DEBUG_CONV_FFT=0 MIOpenDriver conv -F 2 --pad_h 0 --out_channels 64 --fil_w 1 --dilation_w 1 --fil_h 1 --in_h 256 --conv_stride_w 1 --group_count 1 --in_channels 64 --in_w 256 --dilation_h 1 --conv_stride_h 1 --pad_w 0 --batchsize 400 --pad_mode default --mode conv --fil_d 1 --in_d 1 --spatial_dim 2 --conv_stride_d 1 -^ 1 -$ 0 --trans_output_pad_d 0 2>&1`
Segmentation fault

`MIOPEN_LOG_LEVEL=7 MIOPEN_DEBUG_FIND_ONLY_SOLVER=26 MIOPEN_DEBUG_CONV_GEMM=0 MIOPEN_DEBUG_CONV_FFT=0 MIOpenDriver conv -F 1 --pad_h 0 --out_channels 64 --fil_w 1 --dilation_w 1 --fil_h 1 --in_h 256 --conv_stride_w 1 --group_count 1 --in_channels 64 --in_w 256 --dilation_h 1 --conv_stride_h 1 --pad_w 0 --batchsize 400 --pad_mode default --mode conv --fil_d 1 --in_d 1 --spatial_dim 2 --conv_stride_d 1 -^ 1 -$ 0 --trans_output_pad_d 0 2>&1`
Segmentation fault

`MIOPEN_LOG_LEVEL=7 MIOPEN_DEBUG_FIND_ONLY_SOLVER=31 MIOPEN_DEBUG_CONV_GEMM=0 MIOPEN_DEBUG_CONV_FFT=0 MIOpenDriver conv -F 4 --pad_h 1 --out_channels 64 --fil_w 3 --dilation_w 1 --fil_h 3 --in_h 224 --conv_stride_w 1 --group_count 1 --in_channels 64 --in_w 224 --dilation_h 1 --conv_stride_h 1 --pad_w 1 --batchsize 512 --pad_mode default --mode conv --fil_d 1 --in_d 1 --spatial_dim 2 --conv_stride_d 1 -^ 1 -$ 0 --trans_output_pad_d 0 2>&1`
Segmentation fault

-adding to list-

**Comment by JehandadKhan** [comment] 2020-06-24 15:20
@cderb  Please add some log and description of the behavior that occurs.

**Comment by atamazov** [comment] 2020-06-25 11:30
@cderb The 1st case is most likely a duplicate of #264. Please re-test with recent develop than contains a fix (#296). WRT other cases I need logs (level 5 is enough).

**Comment by atamazov** [comment] 2020-06-25 11:54
@cderb The failing configs are huge. How much memory do they need (for buffers and for workspace) and how much memory is installed on your system (including GPU)?

Also I am not sure if all our kernels are able to work with buffers biger than 4 GiB. I guess that Solvers 55, 26, 31 are missing relevant checks. Please address this issue to solver developers.

**Comment by atamazov** [comment] 2020-06-25 12:22
However it seems like we are really touching system limits.

I tried the 1st config on my Radeon VII (16GB GPU, 16GB RAM, 32GB SWAP) with ConvBinWinogradRxS that is really capable to handle huge buffers (`MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvBinWinogradRxS  MIOPEN_DEBUG_CONV_FFT=0 MIOPEN_DEBUG_CONV_GEMM=0 ./bin/MIOpenDriver ...`):
- `conv -H 224 -W 224 -c 64 -n 512 -k 64 -x 3 -y 3 -p 1 -q 1 -F 4 -n 128` - passed
- `conv -H 224 -W 224 -c 64 -n 512 -k 64 -x 3 -y 3 -p 1 -q 1 -F 4 -n 256` - passed
- `conv -H 224 -W 224 -c 64 -n 512 -k 64 -x 3 -y 3 -p 1 -q 1 -F 4 -n 384` - passed
- `conv -H 224 -W 224 -c 64 -n 512 -k 64 -x 3 -y 3 -p 1 -q 1 -F 4 -n 512` - FAILED

Too big buffers (data buffers are of ~6Gib each) eat too much RAM and that leads to numerous system-wide problems like inability to open a pipe to run assembler:
```
...miopen::exec::Run(): popen() failed...
```
Of course HIP and OCL builds would fail under these circumstances.

**Comment by JehandadKhan** [comment] 2020-06-26 17:26
@atamazov  Thanks for the insights, should we check for these limits in MIOpen and filter them out or do we need to improve our available memory checking mechanism ?

**Comment by atamazov** [comment] 2020-06-26 17:32
I am not sure how this could be resolved in the library  (and whether this is possible or not). It is the user's application that allocates resources (system and GPU memory), so it is the app's responsibility to avoid over-allocation, I think.

**Comment by JehandadKhan** [comment] 2020-06-26 17:49
That means this is a bug in the driver ?

**Comment by atamazov** [comment] 2020-06-26 18:00
I wouldn't call this a "bug" :bug: , but yes, the driver could have better diagnostics.

**Closed** 2022-10-19 00:47 UTC
Labels: quality, complexity_high
