### ISSUE TITLE
[driver][convolutions] The verification cache feature is broken

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#2313] opened 2023-08-09 22:22 UTC
The reason is highlighted at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2234#discussion_r1289253848

Let's either remove the feature (`--verification_cache` or `-C`) or revert #2234.

I've collected ~90GB of verification cache files but can survive without it and use GPU verification in _almost all_ cases (except cases when I want to validate the Naive solvers themselves or when HIP compiler is broken). So I prefer reverting #2234 but I am not insisting.

@junliume @JehandadKhan @gonidelis @CAHEK7 what do you think?

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/debugging
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_normal
- Proposed assignees:
  - @gonidelis 
  - @CAHEK7 
  - @atamazov

**Comment by CAHEK7** [comment] 2023-08-10 11:26
Once cache relies on random generator, it is potentially broken all the time. If you just change the sequence of RAND() calls, it produces completely different results. But in some limited cases it may work (the same system, the same libraries, the same test environment).
In that case we kind of changed test environment and we have to live with it, I guess.

The only concern is the random seed - seems I've missed that point and forgot to mention that we need reproduceable tests and thus we need an ability to fix random seed. Currently it is permanently broken because each run it uses random numbers to initialize PRNG.

I vote for that small fix: 
- use the same fixed seed by default
- add an ability to set specific seed or turn on "truly random seed"
- log the seed all the time to be able to make bug reproduction example - just a command line is not enough

**Comment by atamazov** [comment] 2023-08-10 13:51
@CAHEK7 
> Once cache relies on random generator, it is potentially broken all the time.

Absolutely. But there is some difference between potentially broken and really broken, right? For example, I am potentially dead ;)

The proposal looks good, but it does not resolve this specific problem this ticket is about. And it can be implemented with old generator.

**Comment by CAHEK7** [comment] 2023-08-10 14:12
If we want to keep locally gathered cache forever, we must not touch any tests at all. That sounds strange.
The same problem will happen if someone just change the order of tensor initialization or get just a single random value just before the tensors initialization. The only difference is that change affects almost all the tests.

As about the old generator - there were reasons to replace it. But I'm not the person who requested this change and can't say was it really needed and how is this change important. Personally, I don't care much about the updated PRNG.

As about my proposal for old generator - it is not required at all, because by default it was initialized with fixed value.

So, either we revert that change and mark all the related tickets as `won't fix`, or we add an ability to specify random seed and live with updated PRNG and with all of the consequences.

It would be nice to hear the other opinions, I guess.

**Comment by CAHEK7** [comment] 2023-08-10 14:14
`--verification-cache` will work with my proposal, but all of the previously gathered data must be updated.

**Comment by atamazov** [comment] 2023-08-10 14:39
@JehandadKhan What do you think?

**Comment by CAHEK7** [comment] 2023-08-11 12:06
While we are waiting for more feedback, I've prepared a solution based on my proposal. It's kind of trivial.

**Comment by CAHEK7** [comment] 2023-08-23 13:10
10+% time reduction for CI is better than persistent verification cache, so reverting #2234 is not a solution.
Keeping both legacy and new generators is cumbersome and fragile - it's incredibly easy to alter random sequence generation and quite hard to maintain some sort of compatibility between two generators.
So the final solution will be the same as initial one - fix random seed for the new generator to maintain reproducibility and give up on legacy mode and previously generated cache.

One of the proposals for verification cache is to save all input and output data and just load whole state from a disk. It will require much more disk space, but it can be more stable and even can be generated externally from the library.

**Comment by atamazov** [comment] 2023-08-24 23:22
@CAHEK7 
> 10+% time reduction for CI is better than persistent verification cache

This is questionable statement ;)

But let's do not fix this issue.

**Closed as completed** 2023-08-24 23:22 UTC
Labels: urgency_normal, debugging
