### ISSUE TITLE
[hip-igemm] bwd v4r1 computation fail on this miopenDriver config

### ISSUE THREAD

**Issue by carlushuang** [ROCmSoftwarePlatform/MIOpen#636] opened 2020-12-04 08:07 UTC
latest develop branch will have computation fail on this config:
```
./bin/MIOpenDriver conv -n 64 -c 256 -H 56 -W 56 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 2 -t 1

MIOpen Backward Data Conv. Algorithm: 5, Solution: 60/ConvHipImplicitGemmBwdDataV4R1Xdlops
GPU Kernel Time Backward Data Conv. Elapsed: 0.843538 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv1x1u1, 64, 256, 1, 1, 256, 56, 56,  26306674688, 17039360, 205520896, 31186, 264, 0.843538
Backward Convolution Data Failed: 0.215162 > 1.5e-05
```

And this config is OK before this commit (thanks @asleepzzz ):
2a182a8c6a1456f0eace0e4665cc62942c238bbe  RFC: Add code object v4 support (#582)

cc @asroy  @asleepzzz  @sabreshao 

disable find db by `MIOPEN_DEBUG_DISABLE_FIND_DB=1` also will fail

--------------------------------
=> after @asleepzzz  triage, commit: d949000  cause this fault. revert this commit, computation is correct.

update fail log: [bwd-fail-log.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5642249/bwd-fail-log.txt)

**Comment by asleepzzz** [comment] 2020-12-04 08:20
commit 2a182a8c6a1456f0eace0e4665cc62942c238bbe is ok

**Comment by asleepzzz** [comment] 2020-12-04 08:22
after tunning commit d949000495b80d4bc500c39b4e9f615ab996faab,failed

**Comment by asleepzzz** [comment] 2020-12-04 08:31
256-56-56-1x1-256-56-56-64-0x0-1x1-1x1-0-NCHW-FP32-B=miopenConvolutionBwdDataAlgoImplicitGEMM:ConvHipImplicitGemmBwdDataV1R1Xdlops,1.00004,0,miopenConvolutionBwdDataAlgoImplicitGEMM,<unused>;miopenConvolutionBwdDataAlgoDirect:ConvAsm1x1U,1.3629,0,miopenConvolutionBwdDataAlgoDirect,<unused>;miopenConvolutionBwdDataAlgoGEMM:gemm,1.37184,0,rocBlas,<unused>;miopenConvolutionBwdDataAlgoWinograd:ConvBinWinogradRxSf3x2,3.46663,0,miopenConvolutionBwdDataAlgoWinograd,<unused>

**Comment by asleepzzz** [comment] 2020-12-04 08:32
ConvHipImplicitGemmBwdDataV1R1Xdlops not purged ,@asroy

**Comment by asleepzzz** [comment] 2020-12-04 09:35
this issue is very  confusing because it do not use ConvHipImplicitGemmBwdDataV4R1Xdlops,
but it still show Solution is ConvHipImplicitGemmBwdDataV4R1Xdlops

**Comment by atamazov** [comment] 2020-12-04 09:58
I guess that the reason is some of the recent changes that affect PerfConfigs.

We can't use tip of develop for tuning of system databases because tuning procedure is very long. ___So when the next round of tuning begins, there is always some time window when PRs that affect system databases must NOT be merged.___

I think that all the PRs that may affect perf-db records should be marked with `need_find_db_update` and/or `need_perf_db_update` and communicated with @JehandadKhan (e.g. should not be merged in without his explicit approval).

**Comment by atamazov** [comment] 2020-12-04 10:07
Someone please investigate & explain the reason for the failure. The topmost comment says that the failing solver is ConvHipImplicitGemmBwdData***V4***R1Xdlops.

The find-db entry for ConvHipImplicitGemmBwdData***V1***R1Xdlops cannot be the cause of its failure.

**Comment by asleepzzz** [comment] 2020-12-04 10:11
don't rely on the solver name.....
you can back to previous commit and set solver as 60 (ConvHipImplicitGemmBwdDataV4R1Xdlops),
it can pass.....

with the db,the error is 0.25xxx,it must not produced by V4R1....

**Comment by atamazov** [comment] 2020-12-04 10:14
Do you suspect that perf-db record for solver 60 is invalid?

**Comment by asleepzzz** [comment] 2020-12-04 10:18
no , you can't use solver no longer exist in db,
or it will return you a error data,
you can just add V1R1 to the db, select the config you want to try,
add V1R1 as first choice, you can see the issues

**Comment by atamazov** [comment] 2020-12-04 10:19
To check, you can run tuning for the failing problem. Invalid record from the system find-db will be superseded by the user's record. Or you can simply remove the system find-db and check if the solver works fine with default Perf-Config.

**Comment by asleepzzz** [comment] 2020-12-04 10:21
we meet similar issue in jira 258337, just remove ConvHipImplicitGemmBwdDataV1R1Xdlops in db, everything is ok

**Comment by atamazov** [comment] 2020-12-04 10:22
> no , you can't use solver no longer exist in db,
> or it will return you a error data,

This is driver's limitation, not the library's one. I am working on the fix. Can send you a patch for preview, if you wish.

**Comment by atamazov** [comment] 2020-12-04 10:25
> we meet similar issue in jira 258337, just remove ConvHipImplicitGemmBwdDataV1R1Xdlops in db, everything is ok

Are you saying that removal of V1R1 record from the find-db resolves issue in the V4R1 solver???

**Comment by asleepzzz** [comment] 2020-12-04 10:33
You can ignore V4R1.......
Just try add V1R1 everywhere in db to try

**Comment by asleepzzz** [comment] 2020-12-04 10:34
@JehandadKhan

**Comment by atamazov** [comment] 2020-12-04 10:37
> You can ignore V4R1.......

Okay, but then why the topmost comment says that V4R1 was used? Typo?

> Just try add V1R1 everywhere in db to try

I need MI100 node for that, but I do not have it immediately ready to use (I need ~a hour at least to set up).

**Comment by atamazov** [comment] 2020-12-04 10:38
(@asleepzzz thanks for the answers, let's take a break)

**Comment by asleepzzz** [comment] 2020-12-04 10:49
I know this issue is confusing,
logs showed it’s v4r1 and error number is huge
(0.25xxx)

If the config can’t find any solver, it will also return results with huge error

Before jd add protection, we can’t use legacy solver in db.

**Comment by atamazov** [comment] 2020-12-04 10:52
@asleepzzz Please attach some failing log (level 6), I would like to take a look. Thanks.

**Comment by carlushuang** [comment] 2020-12-04 11:06
@atamazov log updated in this issue description

**Comment by atamazov** [comment] 2020-12-04 11:18
From the log I see that V4R1 and GEMM are read from find-db, then Hybrid Find mode decides to use V4R1. Immediate Mode machinery normally reads perf-db, builds the kernels, and so on. Excerpt:
```
MIOpenDriver conv -n 64 -c 256 -H 56 -W 56 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 2 -t 1
MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = HYBRID(3) ...
MIOpen(HIP): Info [HipCompilerVersionImpl] 3.5.20214 ...
MIOpen(HIP): Info [GetBackwardSolutions] ...
MIOpen(HIP): Info2 [FindRecordUnsafe] Looking for key 256-56-56-1x1-256-56-56-64-0x0-1x1-1x1-0-NCHW-FP32-B in file /dockerx/repo/MIOpen/src/kernels/gfx90878.HIP.2_10_0.ufdb.txt
MIOpen(HIP): Info2 [FindRecordUnsafe] Key match: 256-56-56-1x1-256-56-56-64-0x0-1x1-1x1-0-NCHW-FP32-B
MIOpen(HIP): Info2 [FindRecordUnsafe] Contents found: miopenConvolutionBwdDataAlgoImplicitGEMM:ConvHipImplicitGemmBwdDataV4R1Xdlops,0.86096,0,miopenConvolutionBwdDataAlgoImplicitGEMM,<unused>
...
MIOpen(HIP): Info [GetValues] =ConvHipImplicitGemmBwdDataV4R1Xdlops:64,256,1,4,128,64,1,1 ...
MIOpen(HIP): Info2 [Register] Invoker registered for algorithm 256x56x56x1x1x256x56x56x64xNCHWxFP32x0x0x1x1x1x1x1xB and solver ConvHipImplicitGemmBwdDataV4R1Xdlops
MIOpen(HIP): Info2 [SetAsFound1_0] Solver ConvHipImplicitGemmBwdDataV4R1Xdlops registered as find 1.0 best for miopenConvolutionBwdDataAlgoImplicitGEMM in 256x56x56x1x1x256x56x56x64xNCHWxFP32x0x0x1x1x1x1x1xB
MIOpen(HIP): Info [FindConvBwdDataAlgorithm] miopenConvolutionBwdDataAlgoImplicitGEMM	0.86096	0
MIOpen(HIP): Info [FindConvBwdDataAlgorithm] BWD Chosen Algorithm: ConvHipImplicitGemmBwdDataV4R1Xdlops , 0, 0.86096
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info2 [GetInvoker] Returning an invoker for problem 256x56x56x1x1x256x56x56x64xNCHWxFP32x0x0x1x1x1x1x1xB and algorithm miopenConvolutionBwdDataAlgoImplicitGEMM
MIOpen Backward Data Conv. Algorithm: 5, Solution: 60/ConvHipImplicitGemmBwdDataV4R1Xdlops ...
Backward Convolution Data Failed: 0.215162 > 1.5e-05
```
It seems like V4R1 has correctness problems with `PerfConfig = {64,256,1,4,128,64,1,1}`.  Also it could be so that ROCm 3.5 has buggy compiler.

**Comment by atamazov** [comment] 2020-12-04 11:23
Perhaps it is worth looking at the log from the clean experiment. Could you please remove the User Find-db and attach another log. Thanks.

**Comment by atamazov** [comment] 2020-12-04 11:44
@asleepzzz patch for the driver that allows using any solver id in immediate mode: [driver-imm-enable-any-solver.diff.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5642479/driver-imm-enable-any-solver.diff.txt)

**Comment by atamazov** [comment] 2020-12-04 13:16
@asleepzzz #638 adds also support for symbolic names in `-S`.

**Comment by daniellowell** [comment] 2020-12-04 15:42
Typically if the release branch gets too far from the `develop` branch I don't back merge. But you're right that `develop` is always in danger of being in a bad state due to tunings not being in synch with the tip. 

Until we have per-PR tuning we will have this potential hazard. We can keep raising issues and tagging PRs as Artem is suggesting. This is something I've requested from a while back and we need to have discipline on it.

It may be that `develop` will never be full in synch with the tunings. In such a case we need to figure out mitigation strategies. 
- Host all DB in a separate repo tagged with specific commit hash,
- And / Or, inside MIOpen harden it to faulty issues with the databases.

This will continue to be a problem until we solve it. So, we can patch the database, but we need additional strategies.

**Comment by asleepzzz** [comment] 2020-12-04 20:24
there are 3 issues:
1. db use solver which no longer exist
2. after commit 9d2c25012cc3795bc144785ef53f9a5545619771,
if we have some tunning configs can't use , we can THROW it instead of assert in ConvHipImplicitGemmBwdDataV4R1Xdlops::GetSolution  and will not use this config
but I think we need more protection in invoker
@alexandraBara @atamazov @DrizztDoUrden 
3.some corner cases v4r1bwdxdlops do not cover well,
I will update solver to
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/601
@zjing14 
please consider use 
SrcDataPerRead_B = gcd(GemmBThreadDataPerRead_GemmN, SrcDataPerRead_B)
to replace
                if(SrcDataPerRead_B >= GemmBThreadDataPerRead_GemmN)
                {
                    SrcDataPerRead_B = GemmBThreadDataPerRead_GemmN;
                }
in V4R5fwd

**Comment by atamazov** [comment] 2020-12-04 23:32
> if we have some tunning configs can't use , we can THROW it instead of assert in ConvHipImplicitGemmBwdDataV4R1Xdlops::GetSolution

You should implement in the Solver the following method correctly:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/0e0fdd7471d5ea2a75fdab64cdaab5819e8d6f7c/src/include/miopen/solver.hpp#L96-L102
Then the core of the library will do the rest of the job for you. It will throw away invalid PerformanceConfig, issue an error message and regenerate the PerformanceConfig using `yourSolver::GetPerformanceConfig(const ConvolutionContext&)`.

**Comment by atamazov** [comment] 2020-12-04 23:34
> db use solver which no longer exist

Outdate find-db may lead to performance drops. This is known limitation. Correctness issues are not possible provided that the rest of the library is working properly.

**Comment by asleepzzz** [comment] 2020-12-05 02:48
PR 601 not updated yet, I can’t push code now

**Comment by asleepzzz** [comment] 2020-12-05 02:56
IsValidPerformanceConfig Already exist,
Not everytime IsValidPerformanceConfig is called

**Comment by atamazov** [comment] 2020-12-05 17:05
@asleepzzz If you mean that `IsValidPerformanceConfig` is not called when needed (and because of that, the wrong configs come from the perf-db to the solver), then there is a bug in the library core that I am not aware of yet. Please describe the use case scenario so that we can reproduce and fix the bug.

**Comment by asleepzzz** [comment] 2020-12-07 03:18
use this config and close gemm,direct,winograd,
then export MIOPEN_FIND_ENFORCE=4 (important,without this , you can't reproduce)
I have a config which not selected bt current solver, if you need , I can give you the patch
PR 644 can fix 2 issues ,please also help to review

**Comment by atamazov** [comment] 2020-12-07 22:14
@asleepzzz 
> then export MIOPEN_FIND_ENFORCE=4 (important,without this , you can't reproduce)

Do you mean that unwanted behavior happens during tuning?

[off-topic] I highly recommend using markdown formatting, see https://guides.github.com/features/mastering-markdown/

**Comment by atamazov** [comment] 2021-09-27 17:44
It is fixed? By which PR?

**Comment by carlushuang** [comment] 2021-09-29 01:38
@atamazov After discuss with @asleepzzz , after re-tune, the computation is correct

**Closed** 2021-09-29 17:25 UTC
Labels: bug, urgency_blocker
