### ISSUE TITLE
Workspace needed for sub-sample

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#218] opened 2020-05-15 03:12 UTC
We are seeing this error a lot in our CI. I would like to know if it is related to the invoker changes:
```24/62 Test #23: test_immed_conv2d ................***Failed  Error regular expression found in output. Regex=[FAILED]602.66 sec
/var/jenkins/workspace/LLibs_MIOpen_bumpHipClangVersion/build/bin/test_immed_conv2d --float --cmode conv --pmode same --group-count 1 --enable-fdb 1 --input 1, 128, 56, 56 --weights 1, 128, 1, 1 --pads_strides_dilations 0 0 2 2 1 1 --trans_output_pads 0 0 
FAILED: /var/jenkins/workspace/LLibs_MIOpen_bumpHipClangVersion/src/conv/invokers/gcn_asm_1x1u_ss.cpp:56: Workspace is required for SubSample
Forward convolution: 
Input tensor: 1, 128, 56, 56
Weights tensor: 1, 128, 1, 1
Output tensor: 
Filter: conv2d, miopenConvolution, miopenPaddingSame, {0, 0}, {2, 2}, {1, 1}, 
/var/jenkins/workspace/LLibs_MIOpen_bumpHipClangVersion/build/bin/test_immed_conv2d --float --cmode conv --pmode same --group-count 1 --enable-fdb 1 --input 1, 128, 56, 56 --weights 1, 128, 1, 1 --pads_strides_dilations 1 1 2 2 1 1 --trans_output_pads 0 0 
FAILED: /var/jenkins/workspace/LLibs_MIOpen_bumpHipClangVersion/src/conv/invokers/gcn_asm_1x1u_ss.cpp:56: Workspace is required for SubSample
Forward convolution: 
Input tensor: 1, 128, 56, 56
Weights tensor: 1, 128, 1, 1
Output tensor: 
Filter: conv2d, miopenConvolution, miopenPaddingSame, {0, 0}, {2, 2}, {1, 1}, 
/var/jenkins/workspace/LLibs_MIOpen_bumpHipClangVersion/build/bin/test_immed_conv2d --float --cmode conv --pmode same --group-count 1 --enable-fdb 1 --input 1, 128, 56, 56 --weights 1, 128, 1, 1 --pads_strides_dilations 3 3 2 2 1 1 --trans_output_pads 0 0 
FAILED: /var/jenkins/workspace/LLibs_MIOpen_bumpHipClangVersion/src/conv/invokers/gcn_asm_1x1u_ss.cpp:56: Workspace is required for SubSample
Forward convolution: 
Input tensor: 1, 128, 56, 56
Weights tensor: 1, 128, 1, 1
Output tensor: 
Filter: conv2d, miopenConvolution, miopenPaddingSame, {0, 0}, {2, 2}, {1, 1}, 
```

**Comment by atamazov** [comment] 2020-05-15 17:33
The following command (the 1st one from the description) uses Find mode, not Immediate mode, which is weird: `./bin/test_immed_conv2d --float --cmode conv --pmode same --group-count 1 --enable-fdb 1 --input 1, 128, 56, 56 --weights 1, 128, 1, 1 --pads_strides_dilations 0 0 2 2 1 1 --trans_output_pads 0 0 --disable-backward-data --disable-backward-weights`. 

I am looking into the test source...

**Comment by atamazov** [comment] 2020-05-15 17:56
Here https://github.com/AMDComputeLibraries/MLOpen/pull/2110/files?diff=split&w=1#r425960325

**Comment by atamazov** [comment] 2020-05-16 15:22
Possible explanation of reason of the issue is at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/220#issuecomment-629643827

**Comment by aserio** [comment] 2020-05-29 13:40
@atamazov has this issues been resolved with PR#220?

**Comment by atamazov** [comment] 2020-05-29 15:25
> We are seeing this error a lot in our CI.

Maybe. I do not see this in the CI logs of #240 that I am working on (among other things). We can close this after #240 is merged.

**Comment by aserio** [comment] 2020-06-03 15:55
Closing as #240 has been merged.

**Closed by aserio** 2020-06-03 15:55 UTC
Labels: bug, priority_blocker
