### ISSUE TITLE
MIOPEN_USE_COMPOSABLEKERNEL=OFF build error on 6.0

### ISSUE THREAD

**Issue by trixirt** [ROCmSoftwarePlatform/MIOpen#2670] opened 2024-01-12 13:53 UTC
on the rocm-6.0.0 tag, with Fedora Rawhide and gfx90a.

There is this compile error
MIOpen/src/solver/batchnorm/backward_ck.cpp:164:19: error: use of undeclared identifier 'fdesc_problem'; did you mean 'bn_problem'?
  164 |     std::ignore = fdesc_problem;
      |                   ^~~~~~~~~~~~~
      |                   bn_problem
MIOpen/src/solver/batchnorm/backward_ck.cpp:160:81: note: 'bn_problem' declared here
  160 |                                    const miopen::batchnorm::ProblemDescription& bn_problem) const
      |                                                                                 ^

That I think should have been caught in the ci.

**Comment by atamazov** [comment] 2024-01-12 22:47
@trixirt Thanks for informing. This is known problem, fixed in #2464. The fix will be available in further releases.

[Recommendation] When you see an issue at some specific tag/release, please do not hurry up to open a ticket. Why:
- The issue in the past release can't be fixed (in that release, -- because we do not have time machine... likely)
- It is likely that the issue is already fixed and the fix will be available in the future releases.
- Therefore, at first please take the recent `develop` and try to reproduce the issue with it.
  - If the issue is reproducible, then please go ahead and open a ticket.
  - Otherwise the problem is already fixed and the new ticket will be of no use.
    - The exception is if you would like to obtain a patch targeted specifically for the past release to fix it; however that would be an extra work for the MIOpen team that should be well justified.

@junliume I think this can be closed.

**Closed as completed** 2024-01-14 18:24 UTC

**Comment by trixirt** [comment] 2024-01-16 14:09
Yes, i saw this fixed in develop.
The issue is really that the ci should have caught this.
ck has this build problem with some arches [ck issue 775
](https://github.com/ROCm/composable_kernel/issues/775)
so I can not enable ck.
