### ISSUE TITLE
[MLIR][TESTS] test_conv_igemm_mlir* take too much time

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1069] opened 2021-07-30 11:33 UTC
In FP32 gfx908 test, each takes >30 minutes so the overall testing time > 40 minutes. This is too much for Smoke testing. Recommendation:
- Create Full MLIR test stage and move these tests there.
- Create test_conv_igemm_mlir*_small and use these in Smoke.
  - It should contain ~10% from the existing test_conv_igemm_mlir*
  - Tip: _Move_ (not _copy_) test cases from test_conv_igemm_mlir* to *_small to avoid duplication of test cases

Expected time saving is ~27 minutes -> overall testing time should be ~13 mins.

~Alternative, simpler approach: Split 2 existing test_conv_igemm_mlir* tests to 8. Use `CTEST_PARALLEL_LEVEL=8` in Jenkinsfile for MLIR tests. Expected time saving is `~22` minutes -> overall testing time should become `~`18 minutes. Potential problem: too many parallel threads may lead to resource starvation.~ (This won't work)

**Comment by jerryyin** [comment] 2021-07-30 15:49
Thanks for bring this up. It does look like we might be missing the build type in top level cmake, which is causing the excessive amount of test time in those stages. Refer to https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/292.

With this new information, I'm not sure some of the above suggestions still applies. Looks to me `CTEST_PARALLEL_LEVEL=8` is the only relevant one if `test_conv_igemm_mlir` is 10x faster, for example.

**Comment by atamazov** [comment] 2021-07-30 17:10
MIOpen builds Release builds by default. I think that CI spends time for computation of reference convolution data, for validation. Reducing the number of test cases would linearly reduce the testing time.

**Comment by jerryyin** [comment] 2021-09-24 14:49
> MIOpen builds Release builds by default. 

That's right, think I was wrong to assume it was debug build.

>  CI spends time for computation of reference convolution data

I can confirm this when I tested it locally. Now is there a variable like `MIOPEN_DRIVER_USE_GPU_REFERENCE=1` that works for `bin/test_conv2d`? @carlushuang. The variable saved me ton of time in local validation, it seems useful if we can make gpu validation by default on in MIOpen CI in general.

**Comment by atamazov** [comment] 2021-09-24 22:22
@jerryyin 
> The variable saved me ton of time in local validation

Just in case -- I still use the caching feature of the MIOpenDriver -- `MIOpenDriver ... -C ...`

**Comment by atamazov** [comment] 2021-09-24 22:25
> it seems useful if we can make gpu validation by default on in MIOpen CI in general.

Yes, but there are some doubts. And IIRC it only works in the driver, please refer to discussion at #583

**Comment by jerryyin** [comment] 2021-09-27 14:32
@atamazov I actually never knew the `-C` feature. Since the day `MIOPEN_DRIVER_USE_GPU_REFERENCE` becomes available I always use it and it is always fast a reliable for me to validate. 

> Shall we try to add it to the test_conv*? Let's open a ticket if you would like to proceed.

I thought this **was** what @carlushuang planned to do when we talked couple of months ago, so I want to double check with him. But yeah, I don't see a reason to not use such a convenient/efficient feature in CI.

**Comment by atamazov** [comment] 2021-10-03 22:34
> Alternative, simpler approach: Split 2 existing test_conv_igemm_mlir* tests to 8. Use `CTEST_PARALLEL_LEVEL=8` in Jenkinsfile for MLIR tests. Expected time saving is ~22 minutes -> overall testing time should become ~18 minutes. Potential problem: too many parallel threads may lead to resource starvation.

This won't work (let me omit explanations for now).

**Comment by jerryyin** [comment] 2021-11-02 19:03
Closing the ticket as corresponding PR merged. Each individual MLIR smoke test stage now only test 3 configs and finish in around 15 mins.

**Closed by jerryyin** 2021-11-02 19:03 UTC
Labels: performance, testing, urgency_high
