### ISSUE TITLE
No writing to user find-db when fast-hybrid mode is enabled.

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#380] opened 2020-08-14 14:46 UTC
Extension of #299 (implemented in PR #326).
@atamazov Can you or @DrizztDoUrden take this task?

**Comment by aserio** [comment] 2020-08-14 16:39
@daniellowell, what priority should this issue have?

**Comment by atamazov** [comment] 2020-08-18 13:15
@daniellowell Let's reach consensus first.

The idea of "Fast" Find modes is pretty simple: re-use existing code to accelerate Find. The Fast Find mode re-uses existing Immediate mode machinery. The Hybrid mode combines existing Immediate and Find mechanisms (and that is why it is named "Hybrid"); in case of find-db hit we use Immediate mode machinery, in the case of find-db miss we use existing Find machinery. The simplicity of the implementation of these ideas created the false impression that it is possible to move further along this path.

But this is not the case. Fast Hybrid requires modification of Find internals, which is basically a crutch. I warned [from the very beginning](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/299#issuecomment-645698370) that this would be a strange thing.

Now there is an idea to insert another patch, which seems to fix the first crutch. However, this can lead to other problems. After all, we will not only complicate the implementation of Search, but also spoil the functionality of find-db (which by definition is the cache of Find results). I cannot predict what side effects may occur. It is likely that we will need more crutches and patches in the future.

What we get is questionable. Currently, FastHybrid performs Search once (and then re-uses find-db), but after this change, Search will be performed every time. It is faster than a regular Find, but would it be enough? I doubt that this mode (FastHybrid without writing to find-db) will be faster then "normal" Hybrid on average.

That is why I am against making such a decision right now.

However, we can implement this as an experimental feature. Then we'll need to perform a series of measurements to see if this FastHybrid (without writing to find-db) is faster than Hybrid. And even if it is, let's also compare it with "current" FastHybrid. Then we can make a final decision.

If we want to go this way, implementation is not a problem. However let's first decide who will conduct the benchmarking and how to do it.

**Comment by daniellowell** [comment] 2020-08-18 21:42
I agree we shouldn't pile up technical debt for such a thing.
The overall goal is to have the compile time drop drastically for MIOpen generally, but for unseen (therefore untuned) configs specifically. If we can refactor MIOpen to use this hybrid-find mode with a clean design then I think we should do so.
We have 2 domains of MIOpen tuned known configs and untuned unknown configs. If it untuned and unknown, I don't think we should bother compiling tunable source kernels as they would naturally have inferior performance. If the user is a power user then they will know from reading documentation how to tune and how to set the find mode.
So, we should create a design that accomplishes this task.

**Comment by atamazov** [comment] 2020-08-20 13:59
> We have 2 domains of MIOpen tuned known configs and untuned unknown configs. If it untuned and unknown, I don't think we should bother compiling tunable source kernels as they would naturally have inferior performance.

This is a new idea that worth separate ticket.

**Comment by aserio** [comment] 2020-09-22 16:59
Part of the requirement for new dynamic mode. Still in progress

**Comment by atamazov** [comment] 2020-09-22 23:36
@aserio What is new dynamic mode?

**Comment by aserio** [comment] 2020-09-23 13:35
Dynamic Hybrid mode is the new find mode (MIOPEN_FIND_MODE=5). It is similar to Fast Hybrid Find, but in the case of a find_db miss, it will skip all non-dynamic kernels.

**Comment by atamazov** [comment] 2020-09-23 23:29
Thanks. We do not have consensus yet -- if this is requirement or not. Please see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/380#issuecomment-675472170 and https://github.com/ROCmSoftwarePlatform/MIOpen/issues/380#issuecomment-675734858.

**Comment by aserio** [comment] 2020-10-06 16:52
Closing as it is already implemented

**Closed by aserio** 2020-10-06 16:52 UTC
Labels: enhancement, priority_high, request_for_comments

**Comment by atamazov** [comment] 2020-10-07 22:21
> Closing as it is already implemented

Clarification: Assured by design of the Fast Find mode.
