### ISSUE TITLE
MIOpen Build in Docker Image - tons of -Wreserved-identifier warnings

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1322] opened 2021-12-03 05:17 UTC
While Building MIOpen within dockers, I have met tons of warnings caused by

`warning: identifier '_***' is reserved because it starts with '_' followed by a capital letter [-Wreserved-identifier]`

Is there a way to ~~disable~~ **properly fix** them?

UPDATE by @atamazov: To reproduce, pull and run one of the latest HIP mainline builds, e.g. 9148. Install MIOpen's dependencies (of not there already), and build MIOpen with HIP backend.

:warning: Tons of warnings can make your ssh console unresponsive so better redirect stderr and stdout to a file.

**Comment by carlushuang** [comment] 2021-12-03 06:28
seems similiar to https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1314
Is all the compiler bug is because rocm-5.0, the clang++ compiler is upgraded?

**Comment by atamazov** [comment] 2021-12-03 08:37
Those are valid warnings due to usage of reserved identifiers in MIOpen, e.g. addkernels produce them. Of course we can disable the warning, but let's make a proper fix.

**Comment by atamazov** [comment] 2021-12-03 08:39
Maybe @averinevg can you fix these if you have time?

**Comment by averinevg** [comment] 2021-12-03 15:17
@atamazov Ok, I'll see how to fix it

**Comment by atamazov** [comment] 2021-12-03 18:14
@averinevg :+1:

**Comment by atamazov** [comment] 2021-12-06 12:27
@averinevg The topmost comment updated with reproduce instructions. Details by mail or voice.

**Comment by junliume** [comment] 2021-12-16 01:08
@averinevg PR #1340 and #1341 fixed quite a lot of these issues while still some more are observed:
an easy way is to search for `NOLINT (bugprone-reserved-identifier)` within the codebase.
also ref: @shurale-nkn do you know why these NOLINT instructions are not respected and are still generating warnings?

**Comment by atamazov** [comment] 2021-12-16 15:48
@averinevg `__` is a replacement for ellipsis. The function answers the question: "Is parameter belongs to the sequence: {1,4,8,12,16...32}". Just use common sense and invent a new name. For ex, you can use `Is_1_4_8_12_to_32`.

**Comment by averinevg** [comment] 2021-12-21 13:23
All related PRs have been merged. Issue fixed.

**Comment by atamazov** [comment] 2021-12-21 20:26
@averinevg :1st_place_medal:

**Comment by junliume** [comment] 2022-02-05 00:10
@averinevg reopening this issue since if we run `make -j16 check` there are still tons of similar warnings :(
looks like mostly this line, but please check elsewhere too:
```
/root/MIOpen/test/args.hpp:132:10: note: expanded from macro 'ARGS_REQUIRES'
    bool RequiresBool##__LINE__             = true,

**Comment by atamazov** [comment] 2022-02-06 01:09
@junliume I have a fix for it in the hiprtc branch.

**Comment by atamazov** [comment] 2022-02-06 01:10
This is a bug actually.

**Closed** 2022-02-10 08:57 UTC
Labels: quality, complexity_middle, urgency_normal
