### ISSUE TITLE
[MIGraphX] tuning error message with "Attempt to cast AnyInvokeParams to invalid type"

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2239] opened 2023-06-30 20:27 UTC
[Attempt to cast AnyInvokeParams to invalid type.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/11923047/Attempt.to.cast.AnyInvokeParams.to.invalid.type.log)

The log is attached, and we see many errors like the following even though the tuning seems to be finishing without crashing (likely some performance optimization is left on the table though):
```
Compiling ... 
Reading: /dockerx/uif_1.2/1.2-pre-release-migraphx/pt_resnet50v1.5/pt_resnet50v1.5_pruned0.4_1.2_M/float/resnet50_prune0.4_fp16.onnx
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Warning [GetAllConfigs] ConvHipImplicitGemmForwardV4R4Xdlops: Searching the best solution among 0 (spare)...
MIOpen(HIP): Warning [GenericSearch] Done: 0/0/0, best #0 3.40282e+38 4,4,1,4,4,1,0,0,1
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvHipImplicitGemmForwardV4R4Xdlops: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/generic_search.hpp:555: Search failed
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd1x1: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Error [FindSolutionImpl] Search failed for: ConvOclDirectFwd: /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/invoke_params.hpp:98: Attempt to cast AnyInvokeParams to invalid type.
MIOpen(HIP): Warning [GetAllConfigs] ConvHipImplicitGemmForwardV4R4Xdlops: Searching the best solution among 0 (spare)...
MIOpen(HIP): Warning [GenericSearch] Done: 0/0/0, best #0 3.40282e+38 4,4,1,4,4,1,0,0,1

**Comment by junliume** [comment] 2023-06-30 20:29
@DrizztDoUrden @atamazov could you please check under what condition this error message might be triggered? We are asking for a reproduce model too.
```
sudo docker run -it --rm --ipc=host --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --entrypoint bash -e ROCR_VISIBLE_DEVICES=0 -v $HOME/UIF:/dockerx compute-artifactory.amd.com:5000/uif1.2-rel:5.6_67_vai_3.5_py3.8_pytorch1.13_c02cb2e

Navigate to the folder pt_resnet50v1.5_pruned0.4_1.2_M/float/

Run migraphx-driver perf with model file as below

MIOPEN_FIND_ENFORCE=3 migraphx-driver resnet50_prune0.4_fp16.onnx --enable-offload-copy

An error occurs
terminate called after throwing an instance of 'miopen::Exception'                                                              what():  /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/hipoc/hipoc_program.cpp:162: Failed c
reating module from file /tmp/miopen-interim-hsaco-e114-2734-e85d-3ec6/file: shared object initialization failed

Rerun the same command again
```

**Comment by atamazov** [comment] 2023-06-30 23:12
Example command to reproduce:
```bash
MIOPEN_FIND_MODE=normal \
MIOPEN_FIND_ENFORCE=SEARCH_DB_UPDATE \
MIOPEN_USER_DB_PATH=. \
MIOPEN_DEBUG_TUNING_ITERATIONS_MAX=5 \
MIOPEN_DEBUG_CONVOLUTION_ATTRIB_FP16_ALT_IMPL=0 \
MIOPEN_FIND_MODE=normal \
MIOPEN_DEBUG_FIND_ONLY_SOLVER='ConvOclDirectFwd1x1' \
MIOPEN_DEBUG_CONV_DIRECT_OCL_FWD1X1=1 \
MIOPEN_DEBUG_ENABLE_DEPRECATED_SOLVERS=1 \
./bin/test_conv2d --float \
--input 16 16 16 16 --weights 16 16 1 1 --pads_strides_dilations 0 0 1 1 1 1 \
--verbose --disable-backward-data --disable-backward-weights --disable-verification-cache
```
Another solver:
```bash
MIOPEN_FIND_MODE=normal \
MIOPEN_FIND_ENFORCE=SEARCH_DB_UPDATE \
MIOPEN_USER_DB_PATH=. \
MIOPEN_DEBUG_TUNING_ITERATIONS_MAX=5 \
MIOPEN_DEBUG_CONVOLUTION_ATTRIB_FP16_ALT_IMPL=0 \
MIOPEN_FIND_MODE=normal \
MIOPEN_DEBUG_FIND_ONLY_SOLVER='ConvOclDirectFwd' \
MIOPEN_DEBUG_ENABLE_DEPRECATED_SOLVERS=1 \
./bin/test_conv2d --float \
--input 16 16 16 16 --weights 16 16 5 5 --pads_strides_dilations 0 0 1 1 1 1 \
--verbose --disable-backward-data --disable-backward-weights --disable-verification-cache
```

**Comment by atamazov** [comment] 2023-06-30 23:16
@junliume @bghimireamd 
The reason of the issue is a bug in #2154 (committed to develop as 35c64a3bba0c42bb7cb98e7842340e2e4951a102). Previous commit in develop (dfd577e8ff0f73357a83d7e351f0d4eb4b5dd3e9) does not have this problem.

**Comment by atamazov** [comment] 2023-06-30 23:32
The following change is a source of this bug: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2154/files#r1248338279

**Comment by atamazov** [comment] 2023-06-30 23:57
Proposal for the fix: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2154#pullrequestreview-1507982836

**Comment by atamazov** [comment] 2023-07-04 18:39
@junliume @bghimireamd Now this can be closed.

**Closed as completed** 2023-07-06 15:00 UTC
Labels: urgency_blocker, value_unknown
