### ISSUE TITLE
ConvBWD triggers GPU memory access fault on GFX803, not on GFX900

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#84] opened 2019-02-25 03:43 UTC
The command I use for test on GFX803 (Radeon RX 580):
```sh
$ docker run -it --rm --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v /:/ws rocm/tensorflow:rocm2.1-tf1.12-python3 bash

$ python3 benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --num_gpus=1 --batch_size=16 --data_format=NCHW --model=vgg16 --gpu_memory_frac_for_testing=0.8
...
...
2019-02-25 03:33:57.406404: I tensorflow/core/kernels/conv_grad_filter_ops.cc:975] running auto-tune for Backward-Filter
2019-02-25 03:33:58.773280: I tensorflow/core/kernels/conv_grad_input_ops.cc:1023] running auto-tune for Backward-Data
2019-02-25 03:33:58.827405: I tensorflow/core/kernels/conv_grad_filter_ops.cc:975] running auto-tune for Backward-Filter
Memory access fault by GPU node-1 (Agent handle: 0x1f3c420) on address 0xa9be14000. Reason: Page not present or supervisor privilege.
Fatal Python error: Aborted

Thread 0x00007fc220311700 (most recent call first):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407 in _call_tf_sessionrun
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319 in _run_fn
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334 in _do_call
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328 in _do_run
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152 in _run
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929 in run
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 818 in benchmark_one_step
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2316 in benchmark_with_session
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2184 in _benchmark_graph
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1975 in _benchmark_train
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1783 in run
  File "benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 56 in main
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251 in _run_main
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300 in run
  File "benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 60 in <module>
Aborted (core dumped)
```

This issue doesn't happen on Vega 64 (GFX900).

**Comment by atamazov** [comment] 2019-02-25 14:10
We need to identify which config is causing the failure. Please re-run with `MIOPEN_ENABLE_LOGGING=1` and  `MIOPEN_LOG_LEVEL=5` and attach the resulting log to your answer.

> Drag'n'drop works quite fine, but only certain filename extensions are supported by github (which is weird), .txt works for sure.

Please also attach output of ` /opt/rocm/opencl/bin/x86_64/clinfo`.

Also It is good to know MIOpen version, ROCm version. Thanks.

**Comment by Delaunay** [comment] 2019-03-08 18:27
Could this issue be linked to https://github.com/ROCmSoftwarePlatform/pytorch/issues/369 ?

On my side the memory access fault happened with the following configs:
```
./bin/MIOpenDriver conv -n 64 -c 1 -H 128 -W 128 -k 64 -y 5 -x 5 -p 2 -q 2 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpenDriver: conv -n 64 -c 1 -H 128 -W 128 -k 64 -y 5 -x 5 -p 2 -q 2 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpen Forward Conv. Algorithm: 1
GPU Kernel Time Forward Conv. Elapsed: 7.559242 ms (average)
Forward Convolution Verifies on CPU and GPU (1.44903e-08)
MIOpen Backward Data Conv. Algorithm: 1
GPU Kernel Time Backward Data Conv. Elapsed: 2.409337 ms (average)
Memory access fault by GPU node-1 (Agent handle: 0x55922cd58d40) on address 0x502200000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```
and 
```
./bin/MIOpenDriver conv -n 2 -c 32 -H 232 -W 232 -k 3 -y 9 -x 9 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpenDriver: conv -n 2 -c 32 -H 232 -W 232 -k 3 -y 9 -x 9 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpen Forward Conv. Algorithm: 1
GPU Kernel Time Forward Conv. Elapsed: 0.607048 ms (average)
Forward Convolution Verifies on CPU and GPU (1.10376e-07)
MIOpen Backward Data Conv. Algorithm: 3
GPU Kernel Time Backward Data Conv. Elapsed: 0.321356 ms (average)
Memory access fault by GPU node-1 (Agent handle: 0x55b44dc6ed40) on address 0x504000000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

I compiled MIOpen driver from source commit hash is `6c130927bc5`

```
rocm-dev VERSION: 2.1.96
rocm-device-libs VERSION: 0.0.1
rocm-libs VERSION: 2.1.96
hsakmt-roct VERSION: 1.0.9-111-gc65f2de
hsakmt-roct-dev VERSION: 1.0.9-111-gc65f2de
hsa-ext-rocr-dev VERSION: 1.1.9-49-g39f1af5
hsa-rocr-dev VERSION: 1.1.9-49-g39f1af5
hcc VERSION: 1.3.19045
hip_base VERSION: 1.5.19025
hip_hcc VERSION: 1.5.19025

***** Library versions from cmake find_package *****

rocrand VERSION: 1.8.2
hiprand VERSION: 1.8.2
rocblas VERSION: 2.0.1.0
miopen VERSION: 1.7.1
miopengemm VERSION: 1.1.5
rocfft VERSION: 0.8.9.0
rocsparse VERSION: 1.0.1.0
rccl VERSION: 0.7.2-1d8efb9
```

[clinfo.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/2946996/clinfo.txt)

**Comment by sunway513** [comment] 2019-03-10 08:22
Hi @ghostplant , that looks like a known issue on GFX803 target caused by OpenCL toolchain.
Can you try the following workaround and see if that can help:
```
cd ~ && mkdir rocm1.9.2-opencl && cd rocm1.9.2-opencl &&
wget https://www.dropbox.com/s/rtwe1zrpuphbyqm/rocm-opencl-1.2.0-2018111340_amd64.deb && 
wget https://www.dropbox.com/s/6gp2g5zju66i4e9/rocm-opencl-dev-1.2.0-2018111340_amd64.deb && 
sudo dpkg -i rocm-opencl*.deb && rm -rf ~/.cache
```

**Comment by Delaunay** [comment] 2019-03-11 13:14
This seems to fix it for me. I was able to run the two convolutions that were failing.
Do you know if it will be fixed in the next release of rocm-opencl ? Thanks

**Comment by zjing14** [comment] 2019-03-11 16:30
I can reproduce the fault on gfx803. The fault is caused by the MIOpenCvBwdWrW_rdc kernel.

**Comment by daniellowell** [comment] 2019-03-11 16:32
@zjing14 It may be that this is a OpenCL compiler issue. Talk with @sunway513 about the relevant JIRA and please up date the ticket.

**Comment by Delaunay** [comment] 2019-10-06 15:55
Hello, 

I tested the 2 configurations that were failing before.
They works without issue. 

```
(base) setepenre@nas:/opt/rocm/miopen$ ./bin/MIOpenDriver conv -n 64 -c 1 -H 128 -W 128 -k 64 -y 5 -x 5 -p 2 -q 2 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpenDriver: conv -n 64 -c 1 -H 128 -W 128 -k 64 -y 5 -x 5 -p 2 -q 2 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpen Forward Conv. Algorithm: 1
GPU Kernel Time Forward Conv. Elapsed: 3.586353 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv5x5u1, 64, 1, 128, 128, 5, 5, 64,  3355443200, 4200704, 268435456, 936, 76, 3.586353
Forward Convolution Verifies on CPU and GPU (1.54806e-08)
MIOpen Backward Data Conv. Algorithm: 1
GPU Kernel Time Backward Data Conv. Elapsed: 9.127488 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv5x5u1, 64, 1, 5, 5, 64, 128, 128,  3355443200, 22784, 268435456, 368, 29, 9.127488
MIOpen Backward Weights Conv. Algorithm: 1
GPU Kernel Time Backward Weights Conv. Elapsed: 9.152966 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdw-conv5x5u1, 64, 1, 128, 128, 5, 5, 64,  3355443200, 0, 0, 367, 0, 9.152966
Backward Convolution Data Verifies on CPU and GPU (1.65915e-07)
Backward Convolution Weights Verifies on CPU and GPU (1.05621e-07)
(base) setepenre@nas:/opt/rocm/miopen$ ./bin/MIOpenDriver conv -n 2 -c 32 -H 232 -W 232 -k 3 -y 9 -x 9 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpenDriver: conv -n 2 -c 32 -H 232 -W 232 -k 3 -y 9 -x 9 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
MIOpen Forward Conv. Algorithm: 1
GPU Kernel Time Forward Conv. Elapsed: 0.714789 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv9x9u1, 2, 32, 224, 224, 9, 9, 3,  1560674304, 13810048, 1204224, 2183, 21, 0.714789
Forward Convolution Verifies on CPU and GPU (1.10748e-07)
MIOpen Backward Data Conv. Algorithm: 1
GPU Kernel Time Backward Data Conv. Elapsed: 0.750309 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv9x9u1, 2, 32, 9, 9, 3, 224, 224,  1560674304, 31872, 1204224, 2080, 2, 0.750309
MIOpen Backward Weights Conv. Algorithm: 1
GPU Kernel Time Backward Weights Conv. Elapsed: 4.281855 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdw-conv9x9u1, 2, 32, 224, 224, 9, 9, 3,  1560674304, 0, 0, 364, 0, 4.281855
Backward Convolution Data Verifies on CPU and GPU (6.92415e-08)
Backward Convolution Weights Verifies on CPU and GPU (6.87082e-07)
```

**Comment by daniellowell** [comment] 2020-04-06 15:06
Fixed

**Closed by daniellowell** 2020-04-06 15:06 UTC
Labels: non-miopen-bug
