### ISSUE TITLE
Solver workspace should not be part of the Find DB entry

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#2774] opened 2024-02-28 18:59 UTC
By storing this number in the Find Db field, we back ourselves in a corner. If the solver is updated such that the workspace requirement changes, then the Find Db needs to be updated as well, which creates unnecessary churn. 

Furthermore, this information is easily obtainable at runtime. So, why not just ignore the number in the find db? This would improve the robustness of the library and reduce the possibility of mismatch.

**Comment by junliume** [comment] 2024-02-28 23:26
CC: @atamazov 

A quick example:
```
./bin/MIOpenDriver convfp16 -n 32 -c 3 -H 224 -W 224 -k 24 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 4 -t 1
```

**[Observations]:**
```
###:/opt/rocm# ./bin/MIOpenDriver convfp16 -n 32 -c 3 -H 224 -W 224 -k 24 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 4 -t 1
MIOpenDriver convfp16 -n 32 -c 3 -H 224 -W 224 -k 24 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 4 -t 1
PRNG seed: 12345678
MIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/MLOpen/src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp:1253: Not enough workspace has been provided for ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC with fp16 and atomic add.
RunBackwardGPU() FAILED, rc = 0x70000
Backward Convolution Weights FAILED: 1.79769e+308 > 0.082
```
```
###:/opt/rocm# MIOPEN_FIND_MODE=1 ./bin/MIOpenDriver convfp16 -n 32 -c 3 -H 224 -W 224 -k 24 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 4 -t 1
MIOpenDriver convfp16 -n 32 -c 3 -H 224 -W 224 -k 24 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 4 -t 1
PRNG seed: 12345678
MIOpen Backward Weights Conv. Algorithm: 5, Solution: 110/ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC
GPU Kernel Time Backward Weights Conv. Elapsed: 0.147771 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdw-conv3x3u2, 32, 3, 112, 112, 3, 3, 24,  520224768, 0, 0, 3520, 0, 0.147771
Backward Convolution Weights Verifies OK on GPU reference (0 < 0.082)
```

the find DB entry might be playing a role:
```
24-112-112-3x3-3-224-224-32-1x1-2x2-1x1-0-NCHW-FP16-W=ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC:
0.118232,**28905504**,miopenConvolutionBwdWeightsAlgoImplicitGEMM;GemmWrwUniversal:
14.868,677376,miopenConvolutionBwdWeightsAlgoGEMM;ConvDirectNaiveConvWrw:
57.1731,0,miopenConvolutionBwdWeightsAlgoDirect
```
The marked value, if we use FIND_MODE 1, the user DB will generate:
```
24-112-112-3x3-3-224-224-32-1x1-2x2-1x1-0-NCHW-FP16-W=ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC:
0.168065,**28905728**,miopenConvolutionBwdWeightsAlgoImplicitGEMM;GemmWrwUniversal:
16.4458,677376,miopenConvolutionBwdWeightsAlgoGEMM;ConvDirectNaiveConvWrw:
59.4036,0,miopenConvolutionBwdWeightsAlgoDirect
```
hence the marked numerical values: **28905504** vs. **28905728**.

**Comment by atamazov** [comment] 2024-02-29 22:31
@JehandadKhan ~IIRC the already ignore this. We keep this value for backward compatibility of find-db files.~

If we are going to change the format, then let's consider switching from symbolic solver names to numerical IDs etc, at once.

@DrizztDoUrden Please confirm.

**Comment by atamazov** [comment] 2024-02-29 23:31
@JehandadKhan @DrizztDoUrden @junliume It seems like we are still using ws_size from the find-db.

### Tech analysis
- [#1327](https://github.com/ROCm/MIOpen/pull/1327) adds and uses MultiBufferWorkspaceTraits in ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC + more. 
  - MultiBufferWorkspaceTraits adds padding (intended to align the 2nd and subsequent sub-buffers) even if only one buffer is needed.
    - 28905504 = 0x1B91020 - not padded, tuned long ago
    - 28905728 = 0x1B91100 - padded to 256-byte boundary
- Find-db contains values collected before [#1327](https://github.com/ROCm/MIOpen/pull/1327)

So AFAICS the root of this problem is outdated values in find-db.

### I think that one of the reasons of the issue is a flaw in our _process_

While the changes from #1327 are marked with https://github.com/ROCm/MIOpen/labels/IMPACTS_FIND_DB, find-db still contains outdated values. I think we may have to reconsider the process of updating the databases.

### About getting ws size at runtime

I am not against that at all. Of course we'll need to evaluate how this affects the host-size performance, and MLIR solvers may be hit, but this is not a problem to me.

But consider this: ⚠️ Recomputing workspace size each time may camouflage the outdated find-db. And outdated find-db may impact performance. Well, at first it seems better than failure to compute, but after the second thought we'll understand that performance problems may reveal themselves at the MIOpen release phase, and _that_ would be really bad.

**Comment by cderb** [comment] 2024-03-01 21:25
It's true that when failing on workspace size, we can clearly identify a out of date entry for our find db. But running driver commands exhaustively in order to discover and correct these entries seems impractical. It's much more likely that one of these would leak and be encountered by a confused end user.
By moving this to a dynamic calculation we can at least be assured that the commands will work. If not optimally.
Even so, the databases do age and there needs to be more mechanisms for propagating code updates and solver changes to solutions for producing tuned solvers. Perhaps a solid heuristic will help with this in the future. In the mean time there would need to be more tuning patches for solvers which are experiencing significant updates.

**Comment by cderb** [comment] 2024-03-22 23:19
Resolved by 2779

**Closed as completed by cderb** 2024-03-22 23:19 UTC
Labels: urgency_blocker
