### ISSUE TITLE
Hanging fused Winograd kernels on gfx1030

### ISSUE THREAD

**Issue by zjing14** [ROCmSoftwarePlatform/MIOpen#755] opened 2021-02-25 02:20 UTC
Got GPU hangs on gfx1030 with fused Winograd kernels

```
./bin/test_cba_inference --float --input 1, 64, 14, 14 --weights 1, 64, 3, 3 --pads_strides_dilations 0 0 1 1 1 1 --alpha 0.5 --beta 0.5 --gamma 0.5 --bmode 1 --pmode default --test_activ 1 --amode 3
MIOpen(HIP): Info2 [GetKernels] 1 kernels for key: miopenConvolutionWinogradBiasActiv "1, 64, 14, 14FP321, 1, 12, 12FP3264x14x14x3x3x1x12x12x1xNCHWxFP32x0x0x1x1x1x1x1xFbiasOnActivFwd3"
MIOpen(HIP): Info [Execute] miopenConvolutionWinogradBiasActiv,1, 64, 14, 14FP321, 1, 12, 12FP3264x14x14x3x3x1x12x12x1xNCHWxFP32x0x0x1x1x1x1x1xFbiasOnActivFwd3
```

**Comment by Kirpich30000** [comment] 2021-02-25 09:20
@zjing14 could you try #740? Does it resolve the issue?

**Comment by zjing14** [comment] 2021-02-25 17:19
Yes. I tested with #740.

**Comment by atamazov** [comment] 2021-02-25 18:15
@Kirpich30000 how it could be so? I thought #740 is NFC.

**Comment by Kirpich30000** [comment] 2021-02-25 20:05
The first guess is that it might be dispatched with a wrong ndrange or arguments. Does the fusion reuse existing solver or it has it's own machinery for dispatching the kernel?

**Comment by atamazov** [comment] 2021-02-26 18:36
It uses own machinery.

**Comment by atamazov** [comment] 2021-02-26 18:37
#740 merged to develop.

**Comment by zjing14** [comment] 2021-03-02 05:34
@atamazov Do you mean we should drop the issue currently?

**Comment by Kirpich30000** [comment] 2021-03-02 10:26
@zjing14 am I correct, that the issue is still observed even with #740 merged in? We might get confused with `Yes` answering `Does it resolve the issue?` and not `could you try #740?`
If so, does any changes are needed to enable fused Winograd on gfx10?

**Comment by zjing14** [comment] 2021-03-02 14:59
@Kirpich30000 Sorry for the confusion. The hanging issue still exists with #740 merged. 

To enable fused Winograd on gfx10, we need to add gfx1030 into supported arch lists.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f8f7e325cd2a9c2e0a7e3944f226c8b800b87968/src/md_graph.cpp#L507
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f8f7e325cd2a9c2e0a7e3944f226c8b800b87968/src/md_graph.cpp#L617

**Comment by Kirpich30000** [comment] 2021-03-02 15:08
@Slimakanzer please take a look

**Comment by Slimakanzer** [comment] 2021-03-04 10:35
@atamazov
I found some pretty interesting _md_graph_ behavior. It tries to launch the winograd kernel on gfx1030 even without being explicitly added to the `supported_arch .`

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f8f7e325cd2a9c2e0a7e3944f226c8b800b87968/src/md_graph.cpp#L507

As far as I can see, this is the check. However, the debug shows that the `cur.first->supported_arch` vector is always empty, and therefore this check is always true and _md_graph_ tries to launch unsupported kernel.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f8f7e325cd2a9c2e0a7e3944f226c8b800b87968/src/md_graph.cpp#L79

Is this how it should be, or is it a bug?

**Comment by atamazov** [comment] 2021-03-23 19:45
via #772

**Closed** 2021-03-23 19:49 UTC
