### ISSUE TITLE
[TensorFlow] Mysterious Multi-GPU ONLY perf regressions

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2186] opened 2023-06-05 16:08 UTC
**[Claim]**:
For the following benchmark:
> time -p python3 tf_cnn_benchmarks.py --model=vgg11 --num_gpus=4 --batch_size=128 --num_batches=100 --print_training_accuracy=True --optimizer=sgd --variable_update=parameter_server --local_parameter_device=gpu --all_reduce_spec=nccl --variable_update=replicated

By varing the `--num_gpus=` from 1 to 3, the commands invoked on MIOpen do not change. (Verified by attached log)
[TF_vgg11.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/11654470/TF_vgg11.zip) 

It is also verified that there is no single GPU perf regression.

However, more than 10 percent of perf regression is claimed to be caused by MIOpen changes.

**[Diagnostics]**:
Between the claimed passing and failing commits, there are database changes and solver changes for the same configurations:
For example:
from `104/ConvMlirIgemmBwdXdlops` to `84/ConvBinWinogradRxSf2x3g1`
from `105/ConvMlirIgemmWrWXdlops` to `110/ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC`

However, none of these changes, IMHO, should have caused multi-GPU regressions.

![image](https://github.com/ROCmSoftwarePlatform/MIOpen/assets/7841904/b35e908a-fc71-4103-94c1-afc92c857a19)

**Comment by junliume** [comment] 2023-06-05 16:09
@atamazov could you also take a look? Thanks!

**Comment by atamazov** [comment] 2023-06-05 17:58
Please find some known info, questions and observations below. 

- ❓ bbedde37d #2094 
  - Current tip of release/rocm-rel-5.5
  - DOES THIS PASS? There are several DB updates after 819f461f8.
- 779070169 [ROCm 5.5] #2071
- eb02d90fc [ROCm 5.5] #2069
- 3c4796214 [ROCm 5.5] #2046
- e84dd7e14 #2040
- 9cf3f97e7 #2037
- 654b3be68 #2022
- 🔴 819f461f8 #2006 
  - WE KNOW THAT THIS ONE IS FAILING
- 4f4c7f077 #2005
- 99fce6c66 [NFC][ROCm 5.5] Provision changelog for release
- 4b50f338e #1986
- c64258f59 #1969
- 4e16fc551 #1989
- 🟡 d1280cc30 #1984
  - This may lead to performance regressions even if there is other fast iGemm solver exists in the library. This potential regression is fixed by implementing #1987. The PRs that implement it are not included into this release.
- 9259c405e #1966
- 2afc84b00 #1990
- 6d44ce0ad #1978
- 🟢 764bc5193 #1963 
  -  WE KNOW THAT THIS ONE IS PASSING

**Comment by atamazov** [comment] 2023-06-05 18:20
To analyze logs, I need "good" and "bad" ones collected on some multi-GPU node with
```bash
export MIOPEN_ENABLE_LOGGING=1 ;\
export MIOPEN_LOG_LEVEL=6 ;\
export MIOPEN_ENABLE_LOGGING_MPMT=1 ;\
export MIOPEN_ENABLE_LOGGING_ELAPSED_TIME=1
```
Then I'll be able to split the logs per device and try to find out where we are wasting time.

**Comment by atamazov** [comment] 2023-06-05 20:12
@junliume Some more observations. In the total_loss columns, logs show:
- old_1.log: ~7.2 
- old_2.log: **_NaN_** - something is wrong?
- new_2.log: **_NaN_** - something is wrong?

Total images/sec **_regressed_** by 9.2% (1054 vs 965)

**Comment by atamazov** [comment] 2023-06-05 23:12
@junliume 
> Total images/sec **_regressed_** by 9.2% (1054 vs 965)

...which means that the original issue seems reproducible even on the 2-GPU systems.

**Comment by junliume** [comment] 2023-06-06 00:16
[2186.zip.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/11658698/2186.zip.zip)
The attached is the 4 GPU benchmarks with passing and failing docker, with the env vars enabled as suggested by @atamazov

**Comment by junliume** [comment] 2023-06-06 00:25
@rahulbatra85 here is the ticket with more logs

**Comment by atamazov** [comment] 2023-06-06 14:44
@junliume @rahulbatra85 [Notice] While I am analyzing logs (which are huge) it may worth bisecting the list of commits in order to identify the guilty commit.

**Comment by atamazov** [comment] 2023-06-09 15:09
> @junliume @rahulbatra85 [Notice] While I am analyzing logs (which are huge) it may worth bisecting the list of commits in order to identify the guilty commit.

Ping

**Comment by atamazov** [comment] 2023-06-09 15:51
[Informative] ~One of the important differences that I see is several thousands of GetSolution for Winograd in the failing log AFTER the warmup.~ Actually GetSolution is not called. It is the inner lambda (i.e. the Invoker instance) who prints this message at level 6. This can't affect the benchmark unless it is run with MIOPEN_LOG_LEVEL=6 or higher.

**Comment by atamazov** [comment] 2023-06-12 10:24
@junliume Important question: Is it so that 5.5 release candidate is regressed against the **_previous release_**?

**Comment by atamazov** [comment] 2023-06-12 10:30
@junliume The current hypothesis is that the _indirect_ reason of the issue is using ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC instead of ConvMlirIgemmWrWXdlops (for the 128x112x112x3x3x64x112x112x128xNCHWxFP32x1x1x1x1x1x1x1xW config).

In order to check this, I would like to check the logs from both good (764bc5193) and bad (819f461f8) commits taken with settings as specified at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2186#issuecomment-1577261153 _plus_ this:
```
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_FWD_GTC_XDLOPS_NHWC=0
```
Meanwhile I'm preparing a workaround based on this hypothesis (it's not as simple as disabling the solver).

A speculation about the root reason: Maybe some kind of excessive synchronization between streams (which belong to different GPUs) introduced in the 5.5 HIP runtime?

**Comment by atamazov** [comment] 2023-06-13 15:11
## Supposed root cause (1)

This is the result of analyzing logs attached to https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2186#issuecomment-1577718702.

The likely root reason is incorrect handling of HIP streams by TensorFlow.

During the warm-up phase, TF runs one thread per each GPU. It opens and uses one HIP stream in each thread. For example, in passing.log I see thread 8091 and HIP stream 0x5f09530 for GPU 0. This is fine.

After warm-up is done, TF opens additional thread and begins using the same HIP stream in it, in parallel with the original thread. For example, in passing.log you can see that both threads 8091 and 8092 use the same HIP stream 0x5f09530 for GPU 0. In failing.log, TF uses runs kernels on GPU 0 via stream 0x6a94330 from threads 634 and 635. AFAIU this is wrong because HIP streams are not thread-safe and the side effects are not specified.

I suspect that the side effect is excessive synchronization as noted at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2186#issuecomment-1587051176

----
Attached the results of the following commands:

```bash
cat passing-warm.log | grep -E "(8091)|(8092) MIOpen" > passing-warm.log.gpu0
cat failing-warm.log | grep -E "(634)|(635) MIOpen"   > failing-warm.log.gpu0
cat passing-afterwarm.log | grep -E "(8091)|(8092) MIOpen" > passing-afterwarm.log.gpu0
cat failing-afterwarm.log | grep -E "(634)|(635) MIOpen"   > failing-afterwarm.log.gpu0
cat passing-warm.log.gpu0 | grep -E SetStream > passing-warm.log.gpu0.stream
cat failing-warm.log.gpu0 | grep -E SetStream > failing-warm.log.gpu0.stream
cat passing-afterwarm.log.gpu0 | nl | grep -E "(miopenStatus_t miopenConvolution)|(SetStream)" -A 1 > passing-afterwarm.log.gpu0.convstream
cat failing-afterwarm.log.gpu0 | nl | grep -E "(miopenStatus_t miopenConvolution)|(SetStream)" -A 1 > failing-afterwarm.log.gpu0.convstream
```
[issue-2186-analysis-1.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/11736395/issue-2186-analysis-1.zip)

**Comment by atamazov** [comment] 2023-06-13 15:21
@junliume Meanwhile I am working on the W/A as mentioned at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2186#issuecomment-1587051176 and still expecting the logs (as I asked there).

It may also worth collecting the same log but on single GPU (with or without `export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_FWD_GTC_XDLOPS_NHWC=0` -- it does not really matter). What I would like to see is how many threads TF uses when the test is run on a single-GPU system.

Note: It is possible to `export ROCR_VISIBLE_DEVICES=0` on a multi-GPU system to mimic a single-GPU one.

**Comment by junliume** [comment] 2023-06-14 03:31
@atamazov the requested logs are attached:
[failing_detailed.log.bz2.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/11741361/failing_detailed.log.bz2.zip)
[passing_detailed.log.bz2.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/11741363/passing_detailed.log.bz2.zip)

**Comment by atamazov** [comment] 2023-06-21 15:18
The logs do not confirm the hypothesis at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2186#issuecomment-1587051176. The most likely reason is [incorrect test](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2186#issuecomment-1589513681) + some recent changes in HIP runtime that make the problem visible.

I think this is https://github.com/ROCmSoftwarePlatform/MIOpen/labels/non-miopen-bug

**Closed as completed** 2023-07-06 21:27 UTC
Labels: non-miopen-bug

**Comment by atamazov** [comment] 2023-07-06 23:50
@junliume what was the reason?

**Comment by junliume** [comment] 2023-07-08 07:31
@atamazov likely TF microbenchmark issue, and since it is outdated and not maintained the team decides to waive the ticket.
Actually I am curious of the root cause but it's highly likely not MIOpen related.
